---
dependency:
  name: galaxy    
driver:
  name: vagrant
  provider:
  # TODO change provider to libvirt
    name: libvirt
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: CentosStream9
    box: centos/stream9
    box_url: https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-Vagrant-9-20230704.1.x86_64.vagrant-libvirt.box  # https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-Vagrant-9-20230704.1.x86_64.vagrant-virtualbox.box
    memory: 2048
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: "static"
        ip: "192.168.100.10"
    groups:
      - client
  - name: Alma9
    box: almalinux/9
    memory: 2048
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: "static"
        ip: "192.168.100.20"
    groups:
      - client
  - name: ubuntu204
    box: generic/ubuntu2204
    memory: 2048
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: "static"
        ip: "192.168.100.30"
    groups:
      - client
  - name: smbserver
    box: generic/ubuntu2204
    memory: 2048
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: "static"
        ip: "192.168.100.200"
    groups:
      - server
provisioner:
  name: ansible
  inventory:
    host_vars:
      CentosStream9:
        ansible_user: vagrant
        ansible_password: vagrant
      Alma9:
        ansible_user: vagrant
        ansible_password: vagrant
      ubuntu204:
        ansible_user: vagrant
        ansible_password: vagrant
    group_vars:
      all:
        debian_based_distros: ["Debian", "Ubuntu"]
        rhel_based_distros: ["RedHat", "CentOS", "AlmaLinux"]
        mount_targets:
          - { share: "documents", mount: "documents" }
          - { share: "learning", mount: "learning" }
          - { share: "library", mount: "library" }
          - { share: "ressources", mount: "ressources" }
          - { share: "usb_backup", mount: "archive" }
  config_options:
    defaults:
      stdout_callback: debug
      callbacks_enabled: ansible.posix.profile_tasks
      vault_password_file: "$HOME/Documents/vault.pw"
    env:
      ANSIBLE_FORCE_COLOR: "true"
verifier:
  name: ansible
