---
dependency:
  name: galaxy
driver:
  name: vagrant
  parallel: true
  provider:
    name: virtualbox
    type: virtualbox
lint: |
  set -e
  yamllint
  ansible-lint
platforms:
  - name: CentosStream9
    box: centos/stream9
    # box_version: "20230727.1"
    box_url: https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-Vagrant-9-20230727.1.x86_64.vagrant-virtualbox.box
    memory: 2048
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: "static"
        ip: "192.168.56.10"
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--uartmode1', 'disconnected']"
      - "customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']"
      - "customize ['modifyvm', :id, '--vram', '256']"
      - "customize ['modifyvm', :id, '--accelerate-3d', 'off']"
      - "customize ['modifyvm', :id, '--accelerate-2d-video', 'on']"
    groups:
      - client
provisioner:
  name: ansible
  env:
    # ANSIBLE_VERBOSITY: 3
    ANSIBLE_DIFF_ALWAYS: false
  playbooks:
    create: ../template/create.yml
    prepare: ../template/prepare.yml
    converge: ../template/converge.yml
    side_effect: ../template/side_effect.yml
    verify: ../template/verify.yml
    cleanup: ../template/cleanup.yml
  config_options:
    defaults:
      diff: True
      gathering: smart
      fact_caching_timeout: 3600
      fact_caching: jsonfile
      fact_caching_connection: /tmp/ansible_fact_cache
      stdout_callback: debug
      callbacks_enabled: ansible.posix.profile_tasks
    connection:
      pipelining: true
    env:
      ANSIBLE_FORCE_COLOR: "true"
verifier:
  name: ansible
scenario:
  test_sequence:
      - dependency
      - syntax
      - create
      - prepare
      - converge
      - idempotence
      - side_effect
      - verify
      - cleanup
      - destroy
