---
- name: SMB Share
  hosts:
    - fedora
  vars_files:
    - vars.yaml

  tasks:
  #   - name: User home dir path
  #     ansible.builtin.debug:
  #       msg: "This is {{ ansible_env.HOME }} home dir: {{ ansible_env.USER }}"
  #     become_user: root

    - name: Test task as mainws
      ansible.builtin.shell: whoami
      register: me
      become: true

    - name: User home dir path
      ansible.builtin.debug:
        msg: "Thats me {{ me.stdout_lines[0] }}"

    - name: Test task as mainws
      ansible.builtin.shell: whoami
      register: me
      become_user: mainws

    - name: User home dir path
      ansible.builtin.debug:
        msg: "Thats me {{ me.stdout_lines[0] }}"
...
