---

- name: DEBUG

  hosts: dev_host
  become: true

  tasks:
    - name: Install libvirt dependencies
      ansible.builtin.package:
        name: libvirt-devel
        state: present
      become: true

...
