---

# - name: Reset Virtual Machine with Ansible

#   hosts: dev_host

#   roles:
#     - reset_vm

- name: Debug

  hosts: dev_client_fedora
  vars_files:
    - gnome_settings.yaml

  tasks:

    - name: Just ping it
      ansible.builtin.ping:

    - name: Show user environment varibales
      ansible.builtin.debug:
        msg: "{{ user_env_variables }}"

    - name: Show global environment varibales
      ansible.builtin.debug:
        msg: "{{ global_env_variables }}"

...
