---

# - name: Reset Virtual Machine with Ansible

#   hosts: dev_host

#   roles:
#     - reset_vm

- name: Debug

  hosts: dev_client_fedora

  tasks:

    - name: Include gnome settings
      ansible.builtin.include_vars:
        file: gnome_settings.yaml

    - name: Just ping it
      ansible.builtin.ping:

    - name: Get UI users home dir
      ansible.builtin.user:
        name: mainws
        state: present
      register: ui_user

    - name: Show Ui user var
      ansible.builtin.debug:
        msg: "{{ ui_user.home }}"

    # - name: Set top bar button layout
    #   ansible.builtin.command: dconf write /org/gnome/desktop/wm/preferences/button-layout "'appmenu:minimize,maximize,close'"
    #   # gsettings set org.gnome.desktop.wm.preferences button-layout 'close,minimize,maximize:appmenu'
    #   register: command_result
    #   changed_when: command_result.rc == 0
    #   become: true
    #   become_user: mainws

    # - name: Show gsettings result
    #   ansible.builtin.debug:
    #     msg: "{{ command_result }}"

    - name: Configure panel
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      with_dict: "{{ dash_to_panel_settings }}"
      become: true
      become_user: mainws

...
