---

# - name: Reset Virtual Machine with Ansible

#   hosts: dev_host

#   roles:
#     - reset_vm

- name: Debugging

  hosts: dev_host

  tasks:
    - name: Just ping it
      ansible.builtin.ping:

    - name: Copy default config
      ansible.builtin.copy:
        src: /mnt/Projects/coding/config/gnome/gnome_basics_config.yml
        dest: default/

  # roles:
  #   - gnome_config

...
