---

# - name: Reset Virtual Machine with Ansible

#   hosts: dev_host

#   roles:
#     - reset_vm
- name: Debugging

  hosts: dev_client_fedora
  vars:
    picture_src_path: "/mnt/library/ansible/images"
    picture_dest_path: "/var/lib/AccountsService/icons"

  tasks:
    - name: Just ping it
      ansible.builtin.ping:

    - name: Copy profile pictures
      ansible.builtin.copy:
        src: "{{ (picture_src_path, item) | ansible.builtin.path_join }}"
        dest: "{{ (picture_dest_path, item) | ansible.builtin.path_join }}"
        owner: root
        group: root
        mode: '0344'
      loop:
        - "{{ local_user }}"
        - "{{ ansible_user }}"
      become: true

...
