---

# - name: Reset Virtual Machine with Ansible

#   hosts: dev_host

#   roles:
#     - reset_vm

- name: Debug

  hosts: dev_client_fedora

  tasks:
    - name: Just ping it
      ansible.builtin.ping:

    - name: Get UI users home dir
      ansible.builtin.user:
        name: mainws
        state: present
      register: ui_user

    - name: Show Ui user var
      ansible.builtin.debug:
        msg: "{{ ui_user.home }}"

    - name: Set top bar button layout
      ansible.builtin.command: gsettings set org.gnome.desktop.wm.preferences button-layout 'close,minimize,maximize:appmenu'
      register: command_result
      changed_when: command_result.rc == 0
      become: true
      become_user: mainws

    - name: Show gsettings result
      ansible.builtin.debug:
        msg: "{{ command_result }}"

    - name: Set top bar button layout with dconf
      community.general.dconf:
        key: "/org/gnome/desktop/wm/preferences/interface/button-layout"
        value: "'appmenu:minimize,maximize,close'"
      register: dconf_output
      become: true
      become_user: mainws

    - name: Show gsettings result
      ansible.builtin.debug:
        msg: "{{ dconf_output }}"

...
