---

- name: Debug

  hosts: all
  become: true

  tasks:
    - name: Just ping it
      ansible.builtin.ping:

    - name: Install libvirt dependencies
      ansible.builtin.package:
        name: libvirt-devel
        state: present
...
