---

# - name: Reset Virtual Machine with Ansible

#   hosts: dev_host

#   roles:
#     - reset_vm

- name: Debug

  hosts: dev_client_fedora

  tasks:
    - name: Just ping it
      ansible.builtin.ping:

    # - name: Install libvirt dependencies
    #   ansible.builtin.package:
    #     name: libvirt-devel
    #     state: present
    #   become: true

    - name: Show home dir
      ansible.builtin.debug:
        msg: "{{ ansible_env.USER }}"
      become_user: mainws

    # - name: Show username
    #   ansible.builtin.debug:
    #     msg: "{{ ansible_user_id }}"

    # - name: Enable RPM Fusion Free repository
    #   ansible.builtin.yum_repository:
    #     name: rpmfusion-free
    #     description: RPM Fusion Free for Fedora $releasever
    #     metalink: https://mirrors.rpmfusion.org/metalink?repo=free-fedora-$releasever&arch=$basearch
    #     enabled: true
    #     metadata_expire: 14
    #     gpgcheck: true
    #     repo_gpgcheck: false
    #     gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever
    #     state: present
    #   become: true

    # - name: Enable RPM Fusion Non-Free repository
    #   ansible.builtin.yum_repository:
    #     name: rpmfusion-nonfree
    #     description: RPM Fusion Non-Free for Fedora $releasever
    #     metalink: https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-$releasever&arch=$basearch
    #     enabled: true
    #     metadata_expire: 14
    #     gpgcheck: true
    #     repo_gpgcheck: false
    #     gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever
    #     state: present
    #   become: true

    - name: Change to dark
      community.general.dconf:
        key: "/org/gnome/desktop/interface/color-scheme"
        value: "'prefer-dark'"
      become: true
      become_user: mainws

...
