---

# - name: Reset Virtual Machine with Ansible

#   hosts: dev_host

#   roles:
#     - reset_vm

    - name: Just ping it
      ansible.builtin.ping:

    # - name: Check /tmp size
    #   ansible.builtin.shell: |
    #     set -o pipefail
    #     df -h /tmp | awk 'NR==2 {gsub(/G/, "", $4); print $4}'
    #   register: tmp_size
    #   changed_when: false

    # - name: Show output of df
    #   ansible.builtin.debug:
    #     msg: "{{ tmp_size }}"

    - name: Show gnome_user install path
      ansible.builtin.debug:
        msg: "{{ ansible_env }}"

    - name: Show remote home
      ansible.builtin.debug:
        msg: "{{ ansible_env.HOME }}"

    - name: Show TMP
      ansible.builtin.debug:
        msg: "{{ global_env_variables.TMP_DIR }}"

...
