---

# - name: Reset Virtual Machine with Ansible

#   hosts: dev_host

#   roles:
#     - reset_vm

- name: Debug

  hosts: dev_client_fedora
  vars_files:
    - gnome_settings.yaml

  tasks:
    - name: Set system-wide environment variable
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: "TMP_DIR=/tmp/"
        create: true
        mode: "0644"
      become: true

    - name: Show environment
      ansible.builtin.debug:
        msg: "{{ ansible_env }}"

    - name: Show remote home
      ansible.builtin.debug:
        msg: "{{ ansible_env.HOME }}"

    - name: Show TMP
      ansible.builtin.debug:
        msg: "{{ global_env_variables.TMP_DIR }}"

...
