---

- name: Reset Virtual Machine with Ansible

  hosts: dev_host

  roles:
    - reset_vm

- name: Debug

  hosts: dev_client_fedora

  tasks:
    - name: Just ping it
      ansible.builtin.ping:

    # - name: Install libvirt dependencies
    #   ansible.builtin.package:
    #     name: libvirt-devel
    #     state: present
    #   become: true

    - name: Show home dir
      ansible.builtin.debug:
        msg: "{{ ansible_env.HOME }}"

    # - name: Show username
    #   ansible.builtin.debug:
    #     msg: "{{ ansible_user_id }}"

    # - name: Enable RPM Fusion Free repository
    #   ansible.builtin.yum_repository:
    #     name: rpmfusion-free
    #     description: RPM Fusion Free for Fedora $releasever
    #     metalink: https://mirrors.rpmfusion.org/metalink?repo=free-fedora-$releasever&arch=$basearch
    #     enabled: true
    #     metadata_expire: 14
    #     gpgcheck: true
    #     repo_gpgcheck: false
    #     gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever
    #     state: present
    #   become: true

    # - name: Enable RPM Fusion Non-Free repository
    #   ansible.builtin.yum_repository:
    #     name: rpmfusion-nonfree
    #     description: RPM Fusion Non-Free for Fedora $releasever
    #     metalink: https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-$releasever&arch=$basearch
    #     enabled: true
    #     metadata_expire: 14
    #     gpgcheck: true
    #     repo_gpgcheck: false
    #     gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever
    #     state: present
    #   become: true

    - name: Set host name
      ansible.builtin.hostname:
        name: "{{ host_name }}"
        use: systemd
      become: true

    - name: Change GRUB_TIMEOUT to 0
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_TIMEOUT='
        line: 'GRUB_TIMEOUT=0'
        state: present
      become: true

    - name: Set GRUB_TIMEOUT_STYLE to 'hidden'
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_TIMEOUT_STYLE='
        line: 'GRUB_TIMEOUT_STYLE="hidden"'
        state: present
      become: true

    - name: Update GRUB
      ansible.builtin.command: grub2-mkconfig -o /boot/grub2/grub.cfg
      register: grub2_result
      changed_when: grub2_result.rc == 0
      become: true

...
