---

- name: Reset Virtual Machine with Ansible

  hosts: dev_host

  roles:
    - reset_vm

- name: Debug

  hosts: dev_client_fedora

  tasks:

- name: Debug

  hosts: dev_client_fedora
  vars_files:
    - gnome_settings.yaml

  tasks:
    - name: Set system-wide environment variable
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: "TMP_DIR=/tmp/"
        create: true
        mode: "0644"
      become: true

    - name: Show environment
      ansible.builtin.debug:
        msg: "{{ ansible_env }}"

    - name: Show remote home
      ansible.builtin.debug:
        msg: "{{ ansible_env.HOME }}"

    - name: Source TMP_DIR
      ansible.builtin.shell: |
        source /etc/environment
        echo $TMP_DIR
      register: result
      changed_when: false

    - name: Show remote TMP_DIR
      ansible.builtin.debug:
        msg: "{{ result.stdout }}"

...
