---

# - name: Reset Virtual Machine with Ansible

#   hosts: dev_host

#   roles:
#     - reset_vm

# - name: Environment varibales

#   hosts: dev_client_fedora

#   tasks:
#     - name: Set system-wide environment variable
#       ansible.builtin.lineinfile:
#         path: /etc/environment
#         line: "TMP_DIR=/tmp/"
#         create: true
#         mode: "0644"
#       become: true

#     - name: Reboot the host and continue playbook
#       ansible.builtin.reboot:
#         msg: Reboot initiated by Ansible
#         pre_reboot_delay: 5
#         reboot_timeout: 300
#       become: true

#     - name: Wait for the host to come back online
#       ansible.builtin.wait_for_connection:
#         timeout: 300

- name: Debug

  hosts: dev_client_fedora

  tasks:
    - name: Basic usage
      ansible.builtin.debug:
        msg: "'{{ lookup('ansible.builtin.env', 'HOME') }}'"
    # - name: Ensure the environment variable is available
    #   ansible.builtin.command: source /etc/environment
    #   environment:
    #     TMP_DIR: "{{ lookup('ansible.builtin', 'TMP_DIR') }}"
    #   register: source_result
    #   ignore_errors: true
    #   changed_when: false

    # - name: Create the temporary directory if it doesn't exist
    #   ansible.builtin.file:
    #     path: "{{ TMP_DIR }}"
    #     state: directory
    #     mode: "1777"
    #   when: source_result.rc == 0

    # - name: Show temp dir
    #   ansible.builtin.debug:
    #     msg: "{{ env.TMP_DIR }}"
...
