---

- name: Reset Virtual Machine with Ansible

  hosts: dev_host

  roles:
    - reset_vm

- name: Gnome Settings

  hosts: dev_client_fedora

  tasks:
    - name: Include gnome settings
      ansible.builtin.include_vars:
        file: gnome_settings.yaml

    - name: Get UI users home dir
      ansible.builtin.user:
        name: mainws
        state: present
      register: ui_user

    - name: Install pip
      ansible.builtin.package:
        name: pip
        state: present
      become: true

    - name: Install pip psutil package
      ansible.builtin.pip:
        name: psutil
        state: present
      become: true
      become_user: mainws

    - name: Configure gnome-settings
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      with_dict: "{{ gnome_initial_settings }}"
      become: true
      become_user: mainws

    - name: Configure nautilus
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      with_dict: "{{ nautilus_settings }}"
      become: true
      become_user: mainws

    - name: Add terminal profile
      community.general.dconf:
        key: "{{ terminal_profile_list }}"
        value: "['{{ terminal_profile_uuid }}']"
      become: true
      become_user: mainws

    - name: Configure terminal profile
      community.general.dconf:
        key: "{{ terminal_profile_path }}{{ item.key }}"
        value: "{{ item.value }}"
      with_dict: "{{ terminal_profile_settings }}"
      become: true
      become_user: mainws

    - name: Configure terminal legacy settings
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      with_dict: "{{ terminal_legacy_settings }}"
      become: true
      become_user: mainws

    - name: Install gnome tweaks
      ansible.builtin.package:
        name: gnome-tweaks
        state: present
      become: true

    - name: Configure gnome-tweaks
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      with_dict: "{{ gnome_tweaks_settings }}"
      become: true
      become_user: mainws

    - name: Install gnome extensions
      ansible.builtin.package:
        name: gnome-extensions-app
        state: present
      become: true

    - name: Install gtk engine for lavanda theme
      ansible.builtin.package:
        name: gtk-murrine-engine
        state: present
      become: true

    # TODO make extension usable without restart or relogging
    - name: Install user-themes extension
      ansible.builtin.package:
        name: gnome-shell-extension-user-theme
        state: present
      become: true

    - name: Install dash to panel
      ansible.builtin.package:
        name: gnome-shell-extension-dash-to-panel
        state: present
      become: true

    # TODO find a way to reload session without rebooting
    - name: Reboot the host and continue playbook
      ansible.builtin.reboot:
        msg: Reboot initiated by Ansible
        pre_reboot_delay: 5
        reboot_timeout: 300
      become: true

    - name: Wait for the host to come back online
      ansible.builtin.wait_for_connection:
        timeout: 300
      become_user: mainws

    - name: Configure gnome-extensions
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      with_dict: "{{ gnome_extensions_settings }}"
      become: true
      become_user: mainws

    - name: Configure panel
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      with_dict: "{{ dash_to_panel_settings }}"
      become: true
      become_user: mainws

    - name: Install sassc for lavanda theme
      ansible.builtin.package:
        name: sassc
        state: present
      become: true

    - name: Clone lavanda theme from github
      ansible.builtin.git:
        repo: "https://github.com/vinceliuice/Lavanda-gtk-theme.git"
        dest: "{{ ui_user.home }}/Downloads/Lavanda-gtk-theme/"
        single_branch: true
        version: main
      become: true
      become_user: mainws

    # TODO save default download/execution path to variable
    - name: Install lavanda theme
      ansible.builtin.command: "sh {{ ui_user.home }}/Downloads/Lavanda-gtk-theme/install.sh --icon {{ ansible_distribution | lower }}"
      register: install_result
      changed_when: install_result.rc == 0
      become: true
      become_user: mainws

    - name: Clone tela circle icon theme from github
      ansible.builtin.git:
        repo: "https://github.com/vinceliuice/Tela-circle-icon-theme.git"
        dest: "{{ ui_user.home }}/Downloads/Tela-circle-icon-theme/"
        single_branch: true
        version: master
      become: true
      become_user: mainws

    # TODO save default download/execution path to variable
    - name: Install tela circle icon theme
      ansible.builtin.command: "sh {{ ui_user.home }}/Downloads/Tela-circle-icon-theme/install.sh -c purple"
      register: install_result
      changed_when: install_result.rc == 0
      become: true
      become_user: mainws

    - name: Clone Qogir-cursor-theme from github
      ansible.builtin.git:
        repo: "https://github.com/vinceliuice/Qogir-icon-theme.git"
        dest: "{{ ui_user.home }}/Downloads/Qogir-icon-theme/"
        single_branch: true
        version: master
      become: true
      become_user: mainws

    # TODO save default download/execution path to variable
    - name: Install Qogir-cursor-theme
      ansible.builtin.command: "sh {{ ui_user.home }}/Downloads/Qogir-icon-theme/src/cursors/install.sh --theme ubuntu --color dark"
      register: install_result
      changed_when: install_result.rc == 0
      become: true
      become_user: mainws

    - name: Configure gnome themes
      community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      with_dict: "{{ gnome_theme_settings }}"
      become: true
      become_user: mainws

    # TODO delete content of directory
    - name: Remove downloaded repositories
      ansible.builtin.file:
        path: "{{ ui_user.home }}/Downloads/*"
        state: absent
      become: true
      become_user: mainws

...
