---

# - name: Reset Virtual Machine with Ansible

#   hosts: dev_host

#   roles:
#     - reset_vm

- name: Gnome Settings

  hosts: dev_client_fedora

  roles:
    # - gnome_config
    # - gnome_extensions
    - gnome_themes

...
