---

- name: Gnome Settings

  hosts: dev_client_fedora

  tasks:
    - name: Install pip
      ansible.builtin.package:
        name: pip
        state: present
      become: true

    - name: Install pip psutil package
      ansible.builtin.pip:
        name: psutil
        state: present
      become: true
      become_user: mainws

    - name: Change to dark
      community.general.dconf:
        key: "/org/gnome/desktop/interface/color-scheme"
        value: "'prefer-dark'"
      become: true
      become_user: mainws

    - name: Disable hot corner
      community.general.dconf:
        key: "/org/gnome/desktop/interface/org/gnome/desktop/interface"
        value: "false"
      become: true
      become_user: mainws

    - name: Set middle click action to minimize
      community.general.dconf:
        key: "/org/gnome/desktop/wm/preferences/action-middle-click-titlebar"
        value: "'minimize'"
      become: true
      become_user: mainws

    # TODO fix this one doesn't work yet
    # - name: Set top bar button layout
    #   community.general.dconf:
    #     key: "/org/gnome/desktop/wm/preferences/interface/{{ item.key }}"
    #     value: "{{ item.value }}"
    #     state: present
    #   loop:
    #     - { key: "button-layout", value: "'appmenu:minimize,maximize,close'" }
    #   become: true
    #   become_user: mainws

    # TODO make it work
    - name: Set top bar button layout
      ansible.builtin.command: "gsettings set org.gnome.desktop.wm.preferences button-layout 'close,minimize,maximize:appmenu'"
      register: command_result
      changed_when: command_result.rc == 0
      become: true
      become_user: mainws

    - name: Disable attach modal dialogs
      community.general.dconf:
        key: "/org/gnome/mutter/attach-modal-dialogs"
        value: "false"
      become: true
      become_user: mainws

    - name: Don't center new windows
      community.general.dconf:
        key: "/org/gnome/mutter/center-new-windows"
        value: "false"
      become: true
      become_user: mainws

    - name: Set keyboard layout
      community.general.dconf:
        key: "/org/gnome/desktop/input-sources/sources"
        value: "[('xkb', 'de+nodeadkeys')]"
      become: true
      become_user: mainws

    - name: Disable caps lock
      community.general.dconf:
        key: "/org/gnome/desktop/input-sources/xkb-options"
        value: "['caps:none']"
      become: true
      become_user: mainws

    - name: Show weekday in clock
      community.general.dconf:
        key: "/org/gnome/desktop/interface/clock-show-weekday"
        value: "true"
      become: true
      become_user: mainws

    - name: Set interface text
      community.general.dconf:
        key: "/org/gnome/desktop/interface/font-name"
        value: "'Cantarell Bold 11'"
      become: true
      become_user: mainws

    - name: Set titlebar font
      community.general.dconf:
        key: "/org/gnome/desktop/wm/preferences/titlebar-font"
        value: "'Carlito Bold Italic 11'"
      become: true
      become_user: mainws

    - name: Disable show extensions pop-up
      community.general.dconf:
        key: "/org/gnome/tweaks/show-extensions-notice"
        value: "false"
      become: true
      become_user: mainws

    - name: Install gnome tweaks
      ansible.builtin.package:
        name: gnome-tweaks
        state: present
      become: true

    - name: Install gnome extensions
      ansible.builtin.package:
        name: gnome-extensions-app
        state: present
      become: true

    - name: Disable background logo
      community.general.dconf:
        key: "/org/gnome/shell/disabled-extensions"
        value: "['background-logo@fedorahosted.org']"
      become: true
      become_user: mainws

    # TODO install gnome-shell-extension-user-theme that gets hooked automatically into the extensions app

    - name: Install gtk engine for lavanda theme
      ansible.builtin.package:
        name: gtk-murrine-engine
        state: present
      become: true

...
