---

- name: Gnome Settings

  hosts: dev_client_fedora

  tasks:
    - name: Install pip
      ansible.builtin.package:
        name: pip
        state: present
      become: true

    - name: Install pip psutil package
      ansible.builtin.pip:
        name: psutil
        state: present
      become: true
      become_user: mainws

    - name: Change to dark
      community.general.dconf:
        key: "/org/gnome/desktop/interface/color-scheme"
        value: "'prefer-dark'"
      become: true
      become_user: mainws

    # - name: Lock screen notifications
    #   become: true
    #   become_user: mainws
    #   community.general.dconf:
    #     key: "/org/gnome/desktop/notifications/show-in-lock-screen"
    #     value: "false"

...
