local_user: mainws

gnome_extensions_settings:
  "/org/gnome/shell/disabled-extensions": "['background-logo@fedorahosted.org']"
  "/org/gnome/shell/enabled-extensions": "['user-theme@gnome-shell-extensions.gcampax.github.com', 'dash-to-panel@jderose9.github.com', 'appindicatorsupport@rgcjonas.gmail.com', 'GPaste@gnome-shell-extensions.gnome.org', 'drive-menu@gnome-shell-extensions.gcampax.github.com', 'no-overview@fthx', 'system-monitor@paradoxxx.zero.gmail.com', 'tiling-assistant@leleat-on-github']"
download_tmp_dir: "/Downloads/tmp/"
gnome_background_path: "/org/gnome/desktop/background/"
# TODO change hardcoded image path
gnome_background_settings:
  "picture-options": "'zoom'"
  "picture-uri": "'file:///usr/share/backgrounds/Dynamic_Wallpapers/BigSur.xml'"
  "picture-uri-dark": "'file:///usr/share/backgrounds/Dynamic_Wallpapers/BigSur.xml'"
gnome_theme_settings:
  "/org/gnome/shell/extensions/user-theme/name": "'Lavanda-Dark'"
  "/org/gnome/desktop/interface/gtk-theme": "'Lavanda-Dark'"
  "/org/gnome/desktop/interface/icon-theme": "'Tela-circle-purple-dark'"
  "/org/gnome/desktop/interface/cursor-theme": "'Qogir-ubuntu-cursors'"
dash_to_panel_extension_path: "/org/gnome/shell/extensions/dash-to-panel/"
dash_to_panel_extension_settings: 
  "animate-appicon-hover": "false"
  "animate-appicon-hover-animation-convexity": "{'RIPPLE': 2.0, 'PLANK': 1.0, 'SIMPLE': 0.0}"
  "animate-appicon-hover-animation-extent": "{'RIPPLE': 4, 'PLANK': 4, 'SIMPLE': 1}"
  "animate-appicon-hover-animation-type": "'SIMPLE'"
  "appicon-margin": "0"
  "appicon-padding": "6"
  "dot-position": "'BOTTOM'"
  "dot-style-focused": "'DOTS'"
  "dot-style-unfocused": "'DASHES'"
  "group-apps": "true"
  "hotkeys-overlay-combo": "'TEMPORARILY'"
  "intellihide": "true"
  "intellihide-hide-from-windows": "true"
  "leftbox-padding": "-1"
  "leftbox-size": "14"
  "panel-anchors": "{'0':'MIDDLE'}"
  # TODO check why execution fails
  # "/org/gnome/shell/extensions/dash-to-panel/panel-element-positions": "{'0':[{'element':'showAppsButton','visible':true,'position':'stackedTL'},{'element':'activitiesButton','visible':false,'position':'stackedTL'},{'element':'leftBox','visible':true,'position':'stackedTL'},{'element':'taskbar','visible':true,'position':'stackedTL'},{'element':'centerBox','visible':true,'position':'stackedBR'},{'element':'rightBox','visible':true,'position':'stackedBR'},{'element':'dateMenu','visible':true,'position':'stackedBR'},{'element':'systemMenu','visible':true,'position':'stackedBR'},{'element':'desktopButton','visible':true,'position':'stackedBR'}]}"
  "panel-lengths": "{'0':100}"
  "panel-positions": "{'0':'BOTTOM'}"
  "panel-sizes": "{'0':48}"
  "primary-monitor": "0"
  "show-apps-icon-file": "''"
  "status-icon-padding": "4"
  "trans-bg-color": "'#613583'"
  "trans-gradient-bottom-color": "'#613583'"
  "trans-gradient-top-color": "'#dc8add'"
  "trans-panel-opacity": "0.2"
  "trans-use-custom-bg": "true"
  "trans-use-custom-gradient": "true"
  "trans-use-custom-opacity": "true"
  "trans-use-dynamic-opacity": "true"
  "tray-padding": "6"
  "tray-size": "16"
  "window-preview-title-position": "'TOP'"

tiling_assistent_path: "/org/gnome/shell/extensions/tiling-assistant/"
tiling_assistent_settings:
  "enable-tiling-popup": "false"
  "active-window-hint-color": "'rgb(123,136,255)'"
  "restore-window": "['<Super>Down']"
  "tile-bottom-half": "['<Super>KP_2']"
  "tile-top-half": "['<Super>KP_8']"
  "tile-left-half": "['<Super>Left', '<Super>KP_4']"
  "tile-right-half": "['<Super>Right', '<Super>KP_6']"
  "tile-topleft-quarter": "['<Super>KP_7']"
  "tile-topright-quarter": "['<Super>KP_9']"
  "tile-bottomleft-quarter": "['<Super>KP_1']"
  "tile-bottomright-quarter": "['<Super>KP_3']"
monitor_extension_path: "/org/gnome/shell/extensions/system-monitor/"
system_monitor_extension_settings:
  "compact-display": "true"
  "cpu-graph-width": "50"
  "cpu-individual-cores": "false"
  "cpu-style": "'graph'"
  "disk-display": "false"
  "freq-display": "false"
  "gpu-display": "false"
  "memory-graph-width": "50"
  "memory-style": "'graph'"
  "move-clock": "true"
  "net-graph-width": "50"
  "thermal-display": "false"
  "thermal-style": "'graph'"
gpaste_extension_path: "/org/gnome/GPaste/"
gpaste_extension_settings:
  "images-support": "true"
