gnome_initial_settings:
  "/org/gnome/desktop/interface/color-scheme": "'prefer-dark'"
  "/org/gnome/desktop/interface/org/gnome/desktop/interface/enable-hot-corners": "false"
  "/org/gnome/desktop/input-sources/sources": "[('xkb', 'de+nodeadkeys')]"
gnome_tweaks_settings:
  "/org/gnome/desktop/wm/preferences/action-middle-click-titlebar": "'minimize'"
  "/org/gnome/mutter/attach-modal-dialogs": "false"
  "/org/gnome/mutter/center-new-windows": "false"
  "/org/gnome/desktop/input-sources/xkb-options": "['caps:none']"
  "/org/gnome/desktop/interface/clock-show-weekday": "true"
  "/org/gnome/desktop/interface/font-name": "'Cantarell Bold 11'"
  "/org/gnome/desktop/wm/preferences/titlebar-font": "'Carlito Bold Italic 11'"
  "/org/gnome/tweaks/show-extensions-notice": "false"
  # INFO can't be set without graphical session as it seems
  # INFO error: Cannot autolaunch D-Bus without X11 $DISPLAY
  # "/org/gnome/desktop/wm/preferences/interface/button-layout": "'appmenu:minimize,maximize,close'"
gnome_extensions_settings:
  "/org/gnome/shell/disabled-extensions": "['background-logo@fedorahosted.org']"
  "/org/gnome/shell/enabled-extensions": "['user-theme@gnome-shell-extensions.gcampax.github.com', 'dash-to-panel@jderose9.github.com', 'appindicatorsupport@rgcjonas.gmail.com', 'GPaste@gnome-shell-extensions.gnome.org', 'drive-menu@gnome-shell-extensions.gcampax.github.com', 'no-overview@fthx', 'system-monitor@paradoxxx.zero.gmail.com', 'tiling-assistant@leleat-on-github']"
download_tmp_dir: "/Downloads/tmp/"
gnome_background_path: "/org/gnome/desktop/background/"
# TODO change hardcoded image path
gnome_background_settings:
  "picture-options": "'zoom'"
  "picture-uri": "'file:///usr/share/backgrounds/Dynamic_Wallpapers/BigSur.xml'"
  "picture-uri-dark": "'file:///usr/share/backgrounds/Dynamic_Wallpapers/BigSur.xml'"
gnome_theme_settings:
  "/org/gnome/shell/extensions/user-theme/name": "'Lavanda-Dark'"
  "/org/gnome/desktop/interface/gtk-theme": "'Lavanda-Dark'"
  "/org/gnome/desktop/interface/icon-theme": "'Tela-circle-purple-dark'"
  "/org/gnome/desktop/interface/cursor-theme": "'Qogir-ubuntu-cursors'"
dash_to_panel_extension_path: "/org/gnome/shell/extensions/dash-to-panel/"
dash_to_panel_extension_settings: 
  "animate-appicon-hover": "false"
  "animate-appicon-hover-animation-convexity": "{'RIPPLE': 2.0, 'PLANK': 1.0, 'SIMPLE': 0.0}"
  "animate-appicon-hover-animation-extent": "{'RIPPLE': 4, 'PLANK': 4, 'SIMPLE': 1}"
  "animate-appicon-hover-animation-type": "'SIMPLE'"
  "appicon-margin": "0"
  "appicon-padding": "6"
  "dot-position": "'BOTTOM'"
  "dot-style-focused": "'DOTS'"
  "dot-style-unfocused": "'DASHES'"
  "group-apps": "true"
  "hotkeys-overlay-combo": "'TEMPORARILY'"
  "intellihide": "true"
  "intellihide-hide-from-windows": "true"
  "leftbox-padding": "-1"
  "leftbox-size": "14"
  "panel-anchors": "{'0':'MIDDLE'}"
  # TODO check why execution fails
  # "/org/gnome/shell/extensions/dash-to-panel/panel-element-positions": "{'0':[{'element':'showAppsButton','visible':true,'position':'stackedTL'},{'element':'activitiesButton','visible':false,'position':'stackedTL'},{'element':'leftBox','visible':true,'position':'stackedTL'},{'element':'taskbar','visible':true,'position':'stackedTL'},{'element':'centerBox','visible':true,'position':'stackedBR'},{'element':'rightBox','visible':true,'position':'stackedBR'},{'element':'dateMenu','visible':true,'position':'stackedBR'},{'element':'systemMenu','visible':true,'position':'stackedBR'},{'element':'desktopButton','visible':true,'position':'stackedBR'}]}"
  "panel-lengths": "{'0':100}"
  "panel-positions": "{'0':'BOTTOM'}"
  "panel-sizes": "{'0':48}"
  "primary-monitor": "0"
  "show-apps-icon-file": "''"
  "status-icon-padding": "4"
  "trans-bg-color": "'#613583'"
  "trans-gradient-bottom-color": "'#613583'"
  "trans-gradient-top-color": "'#dc8add'"
  "trans-panel-opacity": "0.2"
  "trans-use-custom-bg": "true"
  "trans-use-custom-gradient": "true"
  "trans-use-custom-opacity": "true"
  "trans-use-dynamic-opacity": "true"
  "tray-padding": "6"
  "tray-size": "16"
  "window-preview-title-position": "'TOP'"
nautilus_settings:
  "/org/gnome/nautilus/icon-view/captions": "['detailed_type', 'size', 'date_modified_with_time']"
  "/org/gnome/nautilus/list-view/default-visible-columns": "['name', 'size', 'mime_type', 'date_modified']"
  "/org/gnome/nautilus/list-view/default-column-order": "['name', 'size', 'mime_type', 'date_modified_with_time', 'type', 'owner', 'group', 'permissions', 'where', 'date_modified', 'date_accessed', 'date_created', 'recency', 'starred']"
  "/org/gnome/nautilus/list-view/default-zoom-level": "'small'"
  "/org/gtk/gtk4/settings/file-chooser/sort-directories-first": "true"
  "/org/gtk/gtk4/settings/file-chooser/date-format": "'regular'"
  "/org/gtk/gtk4/settings/file-chooser/location-mode": "'path-bar'"
  "/org/gtk/gtk4/settings/file-chooser/show-hidden": "false"
  "/org/gtk/gtk4/settings/file-chooser/show-size-column": "true"
  "/org/gtk/gtk4/settings/file-chooser/show-type-column": "true"
  "/org/gtk/gtk4/settings/file-chooser/sort-column": "'name'"
  "/org/gtk/gtk4/settings/file-chooser/sort-order": "'ascending'"
  "/org/gtk/gtk4/settings/file-chooser/type-format": "'category'"
  "/org/gtk/gtk4/settings/file-chooser/view-type": "'list'"
  # INFO doesn't seem to work
  # "/org/gnome/nautilus/list-view/default-zoom-level/use-tree-view": "true"
  "/org/gnome/nautilus/preferences/default-folder-viewer": "'list-view'"
  "/org/gnome/nautilus/preferences/migrated-gtk-settings": "true"
  "/org/gnome/nautilus/preferences/search-filter-time-type": "'last_modified'"
  "/org/gnome/nautilus/preferences/show-create-link": "true"
  "/org/gnome/nautilus/preferences/show-delete-permanently": "true"
  "/org/gnome/nautilus/preferences/show-image-thumbnails": "'always'"
terminal_legacy_settings:
  "/org/gnome/terminal/legacy/new-terminal-mode": "'tab'"
terminal_profile_uuid: "5261d7f3-37ae-43cc-90e5-2139da18c41d"
terminal_profile_path: "/org/gnome/terminal/legacy/profiles:/:{{ terminal_profile_uuid }}/"
terminal_profile_list: "/org/gnome/terminal/legacy/profiles:/list"
terminal_profile_settings:
  "visible-name": "'default'"
  "background-color": "'rgb(28,28,28)'"
  "background-transparency-percent": "22"
  "bold-color": "'rgb(147,15,182)'"
  "bold-color-same-as-fg": "false"
  "bold-is-bright": "true"
  "cursor-background-color": "'rgb(84,85,139)'"
  "cursor-colors-set": "true"
  "cursor-foreground-color": "'rgb(163,101,181)'"
  "default-size-columns": "105"
  "default-size-rows": "32"
  "font": "'Liberation Mono 14'"
  "use-system-font": "false"
  "foreground-color": "'rgb(198,141,232)'"
  "highlight-background-color": "'rgb(128,105,128)'"
  "highlight-colors-set": "true"
  "highlight-foreground-color": "'rgb(214,90,232)'"
  "palette": "['rgb(23,20,33)', 'rgb(192,28,40)', 'rgb(38,162,105)', 'rgb(162,115,76)', 'rgb(18,72,139)', 'rgb(163,71,186)', 'rgb(42,161,179)', 'rgb(208,207,204)', 'rgb(94,92,100)', 'rgb(246,97,81)', 'rgb(51,209,122)', 'rgb(233,173,12)', 'rgb(42,123,222)', 'rgb(192,97,203)', 'rgb(51,199,222)', 'rgb(255,255,255)']"
  "scrollbar-policy": "'never'"
  "use-theme-colors": "false"
  "use-transparent-background": "true"
tiling_assistent_path: "/org/gnome/shell/extensions/tiling-assistant/"
tiling_assistent_settings:
  "enable-tiling-popup": "false"
  "active-window-hint-color": "'rgb(123,136,255)'"
  "restore-window": "['<Super>Down']"
  "tile-bottom-half": "['<Super>KP_2']"
  "tile-top-half": "['<Super>KP_8']"
  "tile-left-half": "['<Super>Left', '<Super>KP_4']"
  "tile-right-half": "['<Super>Right', '<Super>KP_6']"
  "tile-topleft-quarter": "['<Super>KP_7']"
  "tile-topright-quarter": "['<Super>KP_9']"
  "tile-bottomleft-quarter": "['<Super>KP_1']"
  "tile-bottomright-quarter": "['<Super>KP_3']"
monitor_extension_path: "/org/gnome/shell/extensions/system-monitor/"
system_monitor_extension_settings:
  "compact-display": "true"
  "cpu-graph-width": "50"
  "cpu-individual-cores": "false"
  "cpu-style": "'graph'"
  "disk-display": "false"
  "freq-display": "false"
  "gpu-display": "false"
  "memory-graph-width": "50"
  "memory-style": "'graph'"
  "move-clock": "true"
  "net-graph-width": "50"
  "thermal-display": "false"
  "thermal-style": "'graph'"
gpaste_extension_path: "/org/gnome/GPaste/"
gpaste_extension_settings:
  "images-support": "true"
