---

- name: Reset Virtual Machine with Ansible

  hosts: dev_host

  roles:
    - reset_vm

- name: Run initial system Setup

  hosts: dev_client_fedora

  tasks:
    - name: Set max_parallel_downloads for dnf
      ansible.builtin.lineinfile:
        path: /etc/dnf/dnf.conf
        regexp: '^max_parallel_downloads='
        line: 'max_parallel_downloads=10'
        state: present
      become: true

    - name: Set fastestmirror=true in dnf.conf
      ansible.builtin.lineinfile:
        path: /etc/dnf/dnf.conf
        regexp: '^fastestmirror='
        line: 'fastestmirror=true'
        state: present
      become: true

    - name: Set fastestmirror=true in dnf.conf
      ansible.builtin.lineinfile:
        path: /etc/dnf/dnf.conf
        regexp: '^deltarpm='
        line: 'deltarpm=true'
        state: present
      become: true

    # TODO renable after moving playbook to role
    # - name: Set host name
    #   ansible.builtin.hostname:
    #     name: "{{ host_name }}"
    #   become: true

    # INFO hit [ESC] or [F4] after vendor logo to show grub2 menu on boot
    - name: Change GRUB_TIMEOUT to 0
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_TIMEOUT='
        line: 'GRUB_TIMEOUT=2'
        state: present
      become: true

    - name: Set GRUB_TIMEOUT_STYLE to 'hidden'
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_TIMEOUT_STYLE='
        line: 'GRUB_TIMEOUT_STYLE="hidden"'
        state: present
      become: true

    - name: Update GRUB
      ansible.builtin.command: grub2-mkconfig -o /boot/grub2/grub.cfg
      register: grub2_result
      changed_when: grub2_result.rc == 0
      become: true

    - name: Upgrade packages
      ansible.builtin.command: dnf upgrade --refresh -y
      register: command_result
      changed_when: command_result.rc == 0
      become: true

    - name: Check for package issues
      ansible.builtin.command: dnf check
      register: command_result
      changed_when: command_result.rc == 0
      become: true

    - name: Remove unused packages
      ansible.builtin.command: dnf autoremove -y
      register: command_result
      changed_when: command_result.rc == 0
      become: true

    # TODO research how neccessary this actually is
    # TODO implement safe check to not let playbook crash
    # - name: Get firmware update devices
    #   ansible.builtin.command: fwupdmgr get-devices
    #   register: command_result
    #   changed_when: command_result.rc == 0
    #   become: true

    # - name: Refresh firmware metadata (force)
    #   ansible.builtin.command: fwupdmgr refresh --force
    #   register: command_result
    #   changed_when: command_result.rc == 0
    #   become: true

    # - name: Get firmware updates
    #   ansible.builtin.command: fwupdmgr get-updates
    #   register: command_result
    #   changed_when: command_result.rc == 0
    #   become: true

    # - name: Apply firmware updates
    #   ansible.builtin.command: fwupdmgr update -y
    #   register: command_result
    #   changed_when: command_result.rc == 0
    #   become: true

    - name: Reboot the host and continue playbook
      ansible.builtin.reboot:
        msg: Reboot initiated by Ansible
        pre_reboot_delay: 5
        reboot_timeout: 300
      become: true

    - name: Wait for the host to come back online
      ansible.builtin.wait_for_connection:
        timeout: 300
      become_user: "{{ ansible_user_id }}"

    - name: Enable RPM Fusion Free repository
      ansible.builtin.yum_repository:
        name: rpmfusion-free
        description: RPM Fusion Free for Fedora $releasever
        metalink: https://mirrors.rpmfusion.org/metalink?repo=free-fedora-$releasever&arch=$basearch
        enabled: true
        metadata_expire: 14
        gpgcheck: true
        repo_gpgcheck: false
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever
        state: present
      become: true

    - name: Enable RPM Fusion Non-Free repository
      ansible.builtin.yum_repository:
        name: rpmfusion-nonfree
        description: RPM Fusion Non-Free for Fedora $releasever
        metalink: https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-$releasever&arch=$basearch
        enabled: true
        metadata_expire: 14
        gpgcheck: true
        repo_gpgcheck: false
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever
        state: present
      become: true

    - name: Install Flatpak
      ansible.builtin.dnf:
        name: flatpak
        state: present
      become: true

    - name: Add Flathub remote
      ansible.builtin.command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      register: command_result
      changed_when: command_result.rc == 0
      become: true

  # roles:
  #   - smb

...
