---

# - name: Reset Unraid Virtual Machine with Ansible

#   hosts: vm_server

#   roles:
#     - reset_unraid_vm

- name: Setup nomachine in vm

  hosts: dev_client_gpu

  roles:
    - nvidia_gpu_driver
    - nomachine_setup

...

# added packsges
# slackware:
# - pkg-config
# - /usr/lib64/pkgconfig/libvirt.pc (custom copy from local system)
#
# pip:
# - wheel
# - libvirt-python==8.7.0
