---

- name: Reset Virtual Machine with Ansible

  hosts: dev_host

  roles:
    - reset_vm

- name: Run initial system Setup

  hosts: dev_client_fedora

  roles:
    - grub_config
    - initial_setup_fedora
    - environment_variables
    - reboot
    - smb

...
