---

# - name: Reset Virtual Machine with Ansible

#   hosts: dev_host

#   roles:
#     - reset_vm

- name: Run initial system Setup

  hosts: dev_client_gpu

  roles:
    - initial_setup_fedora
    - grub_config
    - smb
    - gnome_images

    - gnome_config
    - gnome_extensions
    - gnome_themes
    - vanilla_packages
    - firefox_config
    - thunderbird_setup
    - ulauncher_config
    - meld_setup

...
