---

- name: Run initial system Setup

  hosts: dev_client_fedora

  roles:
    - initial_setup_fedora
    - grub_config
    - smb
    - gnome_images

    - gnome_config
    - gnome_extensions
    - gnome_themes

...
