---

- name: SMB Share

  hosts: ansible-c

  vars_files:
    - vars.yaml

  tasks:
    - name: Set user's home directory path to a variable
      ansible.builtin.set_fact:
        user_home_path: "{{ ansible_env.HOME }}"
      become: false

    - name: Install cifs
      ansible.builtin.package:
        name: cifs-utils
        state: present
      become: true

    - name: Copy credentials file
      ansible.builtin.copy:
        src: ".local/.smb"
        dest: "{{ user_home_path }}/.smb"
        mode: preserve
      become: true

    - name: Create mount point
      ansible.builtin.file:
        path: /{{ mnt_point }}/{{ share_name }}/
        state: directory
        mode: "0755"
      become: true

    - name: Copy mount template to remote host
      ansible.builtin.template:
        src: templates/{{ mnt_point }}-{{ share_name }}.mount.j2
        dest: /etc/systemd/system/{{ mnt_point }}-{{ share_name }}.mount
        mode: preserve
      become: true

    - name: Copy automount template to remote host
      ansible.builtin.template:
        src: templates/{{ mnt_point }}-{{ share_name }}.automount.j2
        dest: /etc/systemd/system/{{ mnt_point }}-{{ share_name }}.automount
        mode: preserve
      become: true
      notify: Reload systemd

    - name: Enable auto-mount file
      ansible.builtin.systemd:
        name: "{{ mnt_point }}-{{ share_name }}.automount"
        state: started
        enabled: true

    - name: Show name
      ansible.builtin.debug:
        msg: "{{ ansible_env.HOME }}"

  handlers:
    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true
...
