---

- name: SMB Share

  hosts: ansible-c

  vars_files:
    - vars.yaml

  tasks:
    - name: Set user's home directory path to a variable
      ansible.builtin.set_fact:
        user_home_path: "{{ ansible_env.HOME }}"
      become: false

    - name: Install cifs
      ansible.builtin.package:
        name: cifs-utils
        state: present
      become: true

    - name: Copy credentials file
      ansible.builtin.copy:
        src: ".local/.smb"
        dest: "{{ user_home_path }}/.smb"
        mode: preserve
      become: true

    - name: Copy mount template to remote host
      ansible.builtin.template:
        src: templates/{{ mnt_point }}-{{ share_name }}.mount.j2
        dest: /etc/systemd/system/{{ mnt_point }}-{{ share_name }}.mount
        mode: preserve
      become: true
      # notify: Reload systemd

    - name: Show name
      ansible.builtin.debug:
        msg: "{{ ansible_env.HOME }}"

...
