---
- name: SMB Share

  hosts:
    - fedora

  vars_files:
    - vars.yaml

  tasks:
    - name: Set user's home directory path to a variable
      ansible.builtin.set_fact:
        user_home_path: "{{ ansible_env.HOME }}"
      become: false

    - name: Install cifs
      ansible.builtin.package:
        name: cifs-utils
        state: present
      become: true
      tags:
        - install-dependencies

    - name: Add fileserver to hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ hosts_entry }}"
        create: true
        mode: "0644"
      become: true
      tags:
        - add-hosts-entry

    - name: Write credentials
      ansible.builtin.copy:
        content: |
          username={{ smb_login }}
          password={{ smb_password }}
        dest: "{{ user_home_path }}/.smb"
        owner: root
        group: root
        mode: "0600"

    - name: Create mount target
      ansible.builtin.file:
        path: /{{ mnt_point }}/{{ item.mount }}/
        state: directory
        owner: root
        group: root
        mode: "0755"
      loop: "{{ target }}"
      become: true

    - name: Copy mount template to remote host
      ansible.builtin.template:
        src: templates/mountfile.mount.j2
        dest: /etc/systemd/system/{{ mnt_point }}-{{ item.mount }}.mount
        mode: preserve
      loop: "{{ target }}"
      become: true

    - name: Copy automount template to remote host
      ansible.builtin.template:
        src: templates/mountfile.automount.j2
        dest: /etc/systemd/system/{{ mnt_point }}-{{ item.mount }}.automount
        mode: preserve
      loop: "{{ target }}"
      become: true

    - name: Enable auto-mount file
      ansible.builtin.systemd:
        daemon_reload: true
        name: "{{ mnt_point }}-{{ item.mount }}.automount"
        state: started
        enabled: true
      loop: "{{ target }}"
      become: true

    - name: Reboot the host and continue playbook
      ansible.builtin.reboot:
        msg: Reboot initiated by Ansible
        pre_reboot_delay: 5
        reboot_timeout: 300

    - name: Wait for the host to come back online
      ansible.builtin.wait_for_connection:
        timeout: 300

    - name: Host is back online
      ansible.builtin.debug:
        msg: "Guess who's back ... back again"

    - name: Copy file using smb shares
      ansible.builtin.command: cp /{{ mnt_point }}/library/dummy_data/setup_check.txt {{ user_home_path }}/Documents/
      become_user: mainws

    - name: Check if the file exists
      ansible.builtin.stat:
        path: ~/Documents/setup_check.txt
      register: file_stat
      become_user: mainws

    - name: File copy check
      ansible.builtin.debug:
        var: file_stat.stat.exists
      become_user: mainws

    - name: Clean up after test
      ansible.builtin.file:
        path: ~/Documents/setup_check.txt
        state: absent
      become_user: mainws
