---

- name: Reset VM
  ansible.builtin.import_playbook: reset_vm.yaml

- name: SMB Share

  hosts:
    - dev_client_fedora

  vars_files:
    - vars.yaml

  tasks:
    - name: Import smb requirements
      ansible.builtin.import_tasks: smb_prerequirements.yaml

    - name: Copy mount template to remote host
      ansible.builtin.template:
        src: templates/mountfile.mount.j2
        dest: /etc/systemd/system/{{ mnt_point }}-{{ item.mount }}.mount
        mode: preserve
      loop: "{{ target }}"
      become: true

    - name: Copy automount template to remote host
      ansible.builtin.template:
        src: templates/mountfile.automount.j2
        dest: /etc/systemd/system/{{ mnt_point }}-{{ item.mount }}.automount
        mode: preserve
      loop: "{{ target }}"
      become: true

    - name: Enable auto-mount file
      ansible.builtin.systemd:
        daemon_reload: true
        name: "{{ mnt_point }}-{{ item.mount }}.automount"
        state: started
        enabled: true
      loop: "{{ target }}"
      become: true

    - name: Reboot the host and continue playbook
      ansible.builtin.reboot:
        msg: Reboot initiated by Ansible
        pre_reboot_delay: 5
        reboot_timeout: 300
      become: true

    - name: Wait for the host to come back online
      ansible.builtin.wait_for_connection:
        timeout: 300
      become_user: mainws

    - name: Check home dir for mainws
      ansible.builtin.debug:
        msg: "This is {{ ansible_env.USER }} currrent home dir: {{ ansible_env.HOME }}"
      become_user: mainws

    - name: Copy file using smb shares
      ansible.builtin.command: cp /{{ mnt_point }}/library/dummy_data/setup_check.txt "{{ ansible_env.HOME }}/Documents/"
      register: copy_result
      changed_when: copy_result.rc == 0
      notify: Clean up after test
      become_user: mainws

  handlers:
    - name: Clean up after test
      ansible.builtin.file:
        path: ~/Documents/setup_check.txt
        state: absent
      become_user: mainws

...
