---

# - name: Reset Virtual Machine with Ansible

#   hosts: dev_host

#   roles:
#     - reset_vm
- name: Debugging

  hosts: dev_host
  become: true

  tasks:
    - name: Just ping it
      ansible.builtin.ping:

    - name: Install htop
      ansible.builtin.package:
        name: htop
        state: present

...
