---

- name: Test stats
  become: true

  hosts:
    - fedora

  vars_files:
    - vars.yaml

  tasks:
    - name: Check if the file exists
      ansible.builtin.stat:
        path: ~/Documents/setup_check.txt
      register: file_stat
      notify: Clean up after test
      become_user: mainws

...
