---
# tasks file for firefox_config

- name: Remove original profile
  ansible.builtin.file:
    path: "{{ (ansible_env.HOME, firefox_config_path) | ansible.builtin.path_join }}"
    state: absent

- name: Recreate firefox default profile
  ansible.builtin.command: firefox -headless -CreateProfile default_profile_by_ansible
  register: result
  changed_when: result.rc == 0

- name: Determine Firefox profile directory
  ansible.builtin.command: "awk -F= '/\\[Profile0\\]/{p=1} p&&/Path/{print $2; exit}' ~/.mozilla/firefox/profiles.ini"
  changed_when: false
  register: profile_directory

- name: Debug profile directory
  ansible.builtin.debug:
    msg: "{{ profile_directory }}"

- name: Populate default profile
  ansible.builtin.command: firefox -headless -P default_profile_by_ansible
  async: 1
  poll: 1
  ignore_errors: true

- name: Create directory if they don't exist
  ansible.builtin.file:
    path: "/{{ policies_path }}"
    state: directory
    owner: root
    group: root
    mode: "0775"
  become: true

- name: copy policies.json to host
  ansible.builtin.copy:
    src: "{{ policies_file }}"
    dest: "/{{ (policies_path, policies_file) | ansible.builtin.path_join }}"
    mode: preserve
  become: true

- name: Copy user.js to host
  ansible.builtin.copy:
    src: "{{ user_config_file }}"
    dest: "{{ (ansible_env.HOME, firefox_config_path, profile_directory.stdout, user_config_file) | ansible.builtin.path_join }}"
    mode: preserve

...
