---

- name: Converge
  hosts: smbserver
  vars_files:
    - ../../../secrets.yml
  become: true
  tasks:
    - name: Initialize SMB server
      ansible.builtin.import_role:
        name: smb_server
        tasks_from: main.yml

- name: Converge
  hosts: client
  vars_files:
    - ../../../secrets.yml
  tasks:
    - name: Include smb role
      ansible.builtin.import_role:
        name: smb
        tasks_from: main.yml
      vars:
        server_host_name: "fileserver"
        server_ip: "192.168.56.200"

...
