---

- name: Converge smb server
  hosts: smbserver
  vars_files:
    - ../../../secrets.yml
  become: true
  tasks:
    - name: Initialize SMB server
      ansible.builtin.import_role:
        name: smb_server
        tasks_from: main.yml

- name: Converge smb client present
  hosts: client
  vars_files:
    - ../../../secrets.yml
  tasks:
    - name: Include smb role present
      ansible.builtin.include_role:
        name: smb
        tasks_from: main.yml
      vars:
        smb_state: present
        smb_server_host_name: "fileserver"
        smb_server_ip: "192.168.56.200"

...
