---
dependency:
  name: galaxy    
driver:
  name: vagrant
  provider:
  # TODO change provider to libvirt
    name: virtualbox
    type: virtualbox
    options:
      memory: 4096
      cpus: 4
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: Alma9
    box: almalinux/9
    memory: 4096
    cpus: 4
    groups:
      - alma9
  - name: ubuntu204
    box: ubuntu/focal64
    memory: 4096
    cpus: 4
    groups:
      - ubuntu
provisioner:
  name: ansible
  inventory:
    host_vars:
      Alma9:
        ansible_user: vagrant
        ansible_password: vagrant
      ubuntu204:
        ansible_user: vagrant
        ansible_password: vagrant
  config_options:
    defaults:
      stdout_callback: debug
      callbacks_enabled: ansible.posix.profile_tasks
      vault_password_file: "$HOME/Documents/vault.pw"
    env:
      ANSIBLE_FORCE_COLOR: "true"
verifier:
  name: ansible
