---

- name: Converge
  hosts: client

  vars:
    dummy_file_path_mount: "/mnt/documents/test.txt"
    dummy_file_path_local: "/tmp/test.txt"

  tasks:
    - name: Reboot the host and continue playbook
      ansible.builtin.reboot:
        msg: Reboot initiated by Ansible
        reboot_timeout: 60
      become: true

    - name: Wait for the host to come back online
      ansible.builtin.wait_for_connection:
        timeout: 300

    # TODO test all mounts points exist
    # TODO test allmount points are able to mount
    # TODO test read file
    # TODO test write file
    # TODO test execute file

    - name: Copy test file to host
      ansible.builtin.copy:
        remote_src: true
        src: "{{ dummy_file_path_mount }}"
        dest: "{{ dummy_file_path_local }}"
        mode: "0600"

    - name: Gather file information
      ansible.builtin.stat:
        path: "{{ dummy_file_path_local }}"
      register: file_info

    - name: Assert file exists
      ansible.builtin.assert:
        that:
          - "file_info.stat.exists"
        fail_msg: "File '{{ dummy_file_path_local }}' does not exist!"
        success_msg: "File '{{ dummy_file_path_local }}' got copied from server successfully!"

    - name: Remove test file
      ansible.builtin.file:
        path: "{{ dummy_file_path_local }}"
        state: absent
