---

# Dependencies tasks for smb_mount

- name: Update apt cache if needed
  when: ansible_os_family in debian_based_distros
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install required packages on redhat based distros
  when: ansible_distribution in rhel_based_distros
  become: true
  ansible.builtin.dnf:
    name: "{{ smb_mount_install_dnf_packages }}"
    state: present

- name: Install required packages on debian based distros
  when: ansible_distribution in debian_based_distros
  become: true
  ansible.builtin.apt:
    name: "{{ smb_mount_install_apt_packages }}"
    state: present

- name: Install required packages on ubuntu
  when: ansible_distribution == "Ubuntu"
  become: true
  ansible.builtin.apt:
    name: "{{ smb_mount_ubuntu_packages }}"
    state: present
  notify: Reboot Host
