---
# tasks file for grub_theme

- name: Regather facts
  ansible.builtin.setup:

- name: Clone Grub2-Themes from github
  ansible.builtin.git:
    repo: "https://github.com/vinceliuice/grub2-themes.git"
    dest: "{{ ansible_env.TMP_DIR }}grub2-themes/"
    single_branch: true
    version: master
    depth: 1

- name: Install Grub2-Themes
  ansible.builtin.command: "./install.sh --theme tela --icon color --screen 1080p --boot"
  args:
    chdir: "{{ ansible_env.TMP_DIR }}grub2-themes/"
  register: install_result
  changed_when: install_result.rc == 0
  become: true

- name: Remove downloaded repositories
  ansible.builtin.file:
    path: "{{ ansible_env.TMP_DIR }}grub2-themes/"
    state: absent

...
