---

# tasks file for meld_setup

- name: Install required packages
  ansible.builtin.package:
    name: "{{ install_packages }}"
    state: present
  become: true

- name: Install pip packages
  ansible.builtin.pip:
    name: "{{ pip_packages }}"
    state: present

- name: Install meld
  ansible.builtin.package:
    name: meld
    state: present
  become: true

- name: Configure meld
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ meld_settings }}"

...
