---
# tasks file for gnome_config

- name: Include vars
  ansible.builtin.include_vars: "/{{ (config_dir, gnome_basic_config_file) | ansible.builtin.path_join }}"
  ignore_errors: true

- name: Combine dictionaries
  ansible.builtin.set_fact:
    combined_settings: "{{ gnome_initial_settings | combine(gnome_tweaks_settings) | combine(nautilus_settings) | combine(terminal_legacy_settings) | combine(terminal_profile_settings) }}"

- name: Install required packages
  ansible.builtin.package:
    name: "{{ install_packages }}"
    state: present
  become: true

- name: Install pip packages
  ansible.builtin.pip:
    name: "{{ pip_packages }}"
    state: present

- name: Show gnome settings
  ansible.builtin.debug:
    msg: "{{ gnome_initial_settings }}"


- name: Configure gnome-settings
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ gnome_initial_settings }}"

# INFO partly broken visible columns show no effect
- name: Configure nautilus
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ nautilus_settings }}"

- name: Add terminal profile
  community.general.dconf:
    key: "{{ terminal_profile_list }}"
    value: "['{{ terminal_profile_uuid }}']"

- name: Configure terminal profile
  community.general.dconf:
    key: "{{ terminal_profile_path }}{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ terminal_profile_settings }}"

- name: Configure terminal legacy settings
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ terminal_legacy_settings }}"

- name: Configure gnome-tweaks
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ gnome_tweaks_settings }}"

...
