---
# tasks file for gnome_config
# TODO check first if gnome is installed -> install if not
# TODO gnome default install highly distro dependent
# evry distro needs their specific install method for gnome and GUI ingeneral
# TODO decide: one role per gnome app or one role for all gnome-apps
# gnome apps: gnome shell, gnome terminal, gedit, nautilus, system-monitor, disk-usage-analyzer, disks, gnome-calendar
# additional apps without own config: gnome-tweaks, gnome-extensions, dconf-editor
# check values using dconf module

- name: Install required packages
  ansible.builtin.package:
    name: "{{ install_packages }}"
    state: present
  become: true

- name: Install pip packages
  ansible.builtin.pip:
    name: "{{ pip_packages }}"
    state: present

- name: Install additional packages
  ansible.builtin.package:
    name: "{{ install_optional_packages }}"
    state: present
  become: true

- name: Configure gnome-settings
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ gnome_initial_settings }}"

# INFO partly broken visible columns show no effect
- name: Configure nautilus
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ nautilus_settings }}"

- name: Configure text editor
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ text_editor_settings }}"

- name: Add terminal profile
  community.general.dconf:
    key: "{{ terminal_profile_list }}"
    value: "['{{ terminal_profile_uuid }}']"

- name: Configure terminal profile
  community.general.dconf:
    key: "{{ terminal_profile_path }}{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ terminal_profile_settings }}"

- name: Configure terminal legacy settings
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ terminal_legacy_settings }}"

- name: Configure gnome-tweaks
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ gnome_tweaks_settings }}"
