---

# tasks file for vanilla_packages
# TODO make sure every install tasks shows all package in output log

- name: Install EPEL repository
  ansible.builtin.dnf:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    disable_gpg_check: true
  when: ansible_distribution == "CentOS"
  become: true

- name: Enable RPM Fusion repositories
  ansible.builtin.dnf:
    name: "{{ item }}"
    disable_gpg_check: true
  loop: "{{ rpm_fusion_repos }}"
  become: true

- name: Install codecs
  ansible.builtin.dnf:
    name: "{{ item.command }}"
    exclude: "{{ item.exclude }}"
    state: present
  loop: "{{ codecs }}"
  become: true

- name: Install dnf packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ centosstream9_repo_packages }}"
  become: true

- name: Remove dnf packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  loop: "{{ remove_packages_centosstream9 }}"
  become: true

- name: Add the flathub flatpak repository remote to the user installation
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install Flatpak packages
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: user
  loop: "{{ flatpak_packages_centosstream9 }}"
  register: flatpak_installation_result

- name: Display installed Flatpak packages
  ansible.builtin.debug:
    var: flatpak_installation_result

...
