---

# tasks file for vanilla_packages

- name: Import RPM Fusion free GPG key
  ansible.builtin.rpm_key:
    key: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020"
    state: present
  become: true

- name: Enable the RPM Fusion free repository
  ansible.builtin.package:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  become: true

- name: Import RPM Fusion nonfree GPG key
  ansible.builtin.rpm_key:
    key: "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020"
    state: present
  become: true

- name: Enable the RPM Fusion nonfree repository
  ansible.builtin.package:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  become: true

- name: Install codecs
  ansible.builtin.dnf:
    name: "{{ item.command }}"
    exclude: "{{ item.exclude }}"
    state: present
  loop: "{{ codecs }}"
  become: true

- name: Install dnf packages
  ansible.builtin.package:
    name: "{{ dnf_packages }}"
    state: present
  become: true

- name: Remove dnf packages
  ansible.builtin.package:
    name: "{{ remove_packages }}"
    state: absent
  become: true

- name: Install flatpak packages
  community.general.flatpak:
    name: "{{ flatpak_packages }}"
    state: present

...
