---

# tasks file for nvidia_gpu_driver

- name: Check for NVIDIA GPU
  ansible.builtin.shell: lspci | grep -i nvidia
  register: gpu_check
  ignore_errors: true
  changed_when: false

- name: Show gpu_check
  ansible.builtin.debug:
    msg: "{{  gpu_check }}"

# TODO check based on package list (package_facts)
- name: Check if nvidia gpu driver is installed
  ansible.builtin.command: rpm -q akmod-nvidia
  register: package_check
  when: ansible_facts['os_family'] == "RedHat" and gpu_check.rc == 0
  changed_when: false
  ignore_errors: true

- name: Update GDM configuration file
  ansible.builtin.lineinfile:
    path: /etc/gdm/custom.conf
    backrefs: true
    regexp: '^#WaylandEnable=false$'
    line: 'WaylandEnable=false\nDefaultSession=gnome-xorg.desktop'
    state: present
  when: gpu_check.rc == 0
  become: true

- name: Reboot the host and continue playbook
  ansible.builtin.reboot:
    msg: Reboot initiated by Ansible
    pre_reboot_delay: 5
    reboot_timeout: 300
  when: gpu_check.rc == 0
  become: true

- name: Wait for the host to come back online
  ansible.builtin.wait_for_connection:
    timeout: 300
  when: gpu_check.rc == 0

# TODO update based on installed packages and/or control version
- name: Update all packages
  ansible.builtin.package:
    name: '*'
    state: latest
    update_cache: true
  when: gpu_check.rc == 0
  become: true

- name: Install EPEL repository
  ansible.builtin.dnf:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    disable_gpg_check: true
  when: gpu_check.rc == 0 and ansible_distribution == 'CentOS'
  become: true

- name: Enable RPM Fusion repositories
  ansible.builtin.dnf:
    name: "{{ item }}"
    disable_gpg_check: true
  loop: "{{ rpm_fusion_repos }}"
  when: gpu_check.rc == 0
  become: true

- name: Install required packages
  ansible.builtin.package:
    name: "{{ install_packages }}"
    state: present
  when: gpu_check.rc == 0
  become: true

- name: Reboot the host and continue playbook
  ansible.builtin.reboot:
    msg: Reboot initiated by Ansible
    pre_reboot_delay: 5
    reboot_timeout: 300
  when: gpu_check.rc == 0
  become: true

- name: Wait for the host to come back online
  ansible.builtin.wait_for_connection:
    timeout: 300
  when: gpu_check.rc == 0

...
