---

- name: Create and configure gnome desktop
  hosts: client
  tasks:
    - name: Include gnome role present
      ansible.builtin.include_role:
        name: gnome_setup
        tasks_from: main.yml
      vars:
        gnome_setup_state: present
        smb_mount_server_host_name: "fileserver"
        smb_mount_server_ip: "192.168.56.200"

...
