---

- name: Create and configure gnome desktop
  hosts: client
  tasks:
    - name: Include gnome role present
      ansible.builtin.include_role:
        name: gnome_setup
      vars:
        gnome_setup_state: present

...
