---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  # no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Stop and remove VMs
      delegate_to: localhost
      ansible.builtin.command:
        cmd: "vagrant destroy -f"
      args:
        chdir: "{{ hostvars[inventory_hostname].molecule_ephemeral_directory }}"
      register: result
      changed_when: result.rc == 0

    # Mandatory configuration for Molecule to function.

    - name: Populate instance config
      ansible.builtin.set_fact:
        instance_conf: {}

    - name: Dump instance config
      ansible.builtin.copy:
        content: |
          # Molecule managed

          {{ instance_conf | to_json | from_json | to_yaml }}
        dest: "{{ molecule_instance_config }}"
        mode: "0600"
      when: server.changed | default(false) | bool  # noqa no-handler
