---
dependency:
  name: galaxy
driver:
  name: vagrant
  parallel: true
  snapshot: initial
  provider:
    name: virtualbox
    type: virtualbox
lint: |
  set -e
  yamllint
  ansible-lint
platforms:
  # TODO check how to fix Error: Failed to download metadata for repo 'baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
  # https://www.reddit.com/r/CentOS/comments/18ard59/is_there_something_wrong_with_cs9_dnfyum/
  - name: CentosStream9
    box: centos/stream9
    box_url: https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-Vagrant-9-20230501.0.x86_64.vagrant-virtualbox.box
    memory: 2048
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: "static"
        ip: "192.168.56.10"
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--uartmode1', 'disconnected']"
      - "customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']"
      - "customize ['modifyvm', :id, '--vram', '256']"
      - "customize ['modifyvm', :id, '--accelerate-3d', 'off']"
      - "customize ['modifyvm', :id, '--accelerate-2d-video', 'on']"
    groups:
      - client
  # - name: Alma9
  #   box: almalinux/9
  #   memory: 2048
  #   cpus: 2
  #   interfaces:
  #     - auto_config: true
  #       network_name: private_network
  #       type: "static"
  #       ip: "192.168.56.20"
  #   provider_raw_config_args:
  #     - "customize ['modifyvm', :id, '--uartmode1', 'disconnected']"
  #     - "customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']"
  #     - "customize ['modifyvm', :id, '--vram', '256']"
  #     - "customize ['modifyvm', :id, '--accelerate-3d', 'off']"
  #     - "customize ['modifyvm', :id, '--accelerate-2d-video', 'on']"
  #   groups:
  #     - client
  # - name: Rocky9
  #   box: rockylinux/9
  #   memory: 2048
  #   cpus: 2
  #   interfaces:
  #     - auto_config: true
  #       network_name: private_network
  #       type: "static"
  #       ip: "192.168.56.30"
  #   provider_raw_config_args:
  #     - "customize ['modifyvm', :id, '--uartmode1', 'disconnected']"
  #     - "customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']"
  #     - "customize ['modifyvm', :id, '--vram', '256']"
  #     - "customize ['modifyvm', :id, '--accelerate-3d', 'off']"
  #     - "customize ['modifyvm', :id, '--accelerate-2d-video', 'on']"
  #   groups:
  #     - client
  - name: Ubuntu2210
    box: ubuntu/jammy64
    memory: 2048
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: "static"
        ip: "192.168.56.40"
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--uartmode1', 'disconnected']"
      - "customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']"
      - "customize ['modifyvm', :id, '--vram', '256']"
      - "customize ['modifyvm', :id, '--accelerate-3d', 'off']"
      - "customize ['modifyvm', :id, '--accelerate-2d-video', 'on']"
    groups:
      - client
  # - name: Debian12
  #   box: debian/bookworm64
  #   memory: 2048
  #   cpus: 2
  #   interfaces:
  #     - auto_config: true
  #       network_name: private_network
  #       type: "static"
  #       ip: "192.168.56.50"
  #   provider_raw_config_args:
  #     - "customize ['modifyvm', :id, '--uartmode1', 'disconnected']"
  #     - "customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']"
  #     - "customize ['modifyvm', :id, '--vram', '256']"
  #     - "customize ['modifyvm', :id, '--accelerate-3d', 'off']"
  #     - "customize ['modifyvm', :id, '--accelerate-2d-video', 'on']"
  #   groups:
  #     - client
provisioner:
  name: ansible
  env:
    # ANSIBLE_VERBOSITY: 3
    ANSIBLE_DIFF_ALWAYS: false

  inventory:
    host_vars:
      CentosStream9:
        ansible_user: vagrant
        ansible_password: vagrant
      Alma9:
        ansible_user: vagrant
        ansible_password: vagrant
      ubuntu2204:
        ansible_user: vagrant
        ansible_password: vagrant
      debian12:
        ansible_user: vagrant
        ansible_password: vagrant
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
        ansible_timeout: 180
        redhat: "RedHat"
        debian: "Debian"
        debian_based_distros: ["Debian", "Ubuntu"]
        rhel_based_distros: ["RedHat", "CentOS", "AlmaLinux"]
        system_local_lang: "en_US.UTF-8"
        mount_targets:
          - { share: "documents", mount: "documents" }
          - { share: "learning", mount: "learning" }
          - { share: "library", mount: "library" }
          - { share: "ressources", mount: "ressources" }
          - { share: "usb_backup", mount: "archive" }
        install_name: install 
  config_options:
    defaults:
      diff: True
      gathering: smart
      fact_caching_timeout: 3600
      fact_caching: jsonfile
      fact_caching_connection: /tmp/ansible_fact_cache
      stdout_callback: debug
      callbacks_enabled: ansible.posix.profile_tasks
      vault_password_file: "$HOME/Documents/vault.pw"
    connection:
      # WARNING disable "requiretty" in hosts sudoers file on case of errors
      pipelining: true
    env:
      ANSIBLE_FORCE_COLOR: "true"
scenario:
  destroy_sequence:
    - destroy
verifier:
  name: ansible
