---

- name: Verify
  hosts: client

  vars_files:
    - ../../../gnome_setup/defaults/main.yml
    - ../../../gnome_setup/vars/main.yml

  tasks:
    # gather package facts:
    - name: Gather package facts
      ansible.builtin.package_facts:

    # check enabled repos
    - name: Get repos on rhel based systems
      when: ansible_os_family == "RedHat"
      block:
        - name: Get enabled repos
          ansible.builtin.shell:
            cmd: "dnf repolist --enabled | awk '{print $1}'"
          register: enabled_repos
          changed_when: false

        - name: Test enabled repos
          ansible.builtin.assert:
            that:
              - item in enabled_repos.stdout_lines
            fail_msg: "Repo {{ item }} is missing"
            quiet: true
          loop:
            - crb
            - epel
            - rpmfusion-free-updates
            - rpmfusion-nonfree-updates

    # check installed requirements
    - name: Test installed requirements
      ansible.builtin.assert:
        that:
          - item in ansible_facts.packages
        fail_msg: "Required package {{ item }} is missing"
        quiet: true
      loop: "{{ dependencies[ansible_os_family] }}"

    # check installed packages
    - name: Test installed gnome packages
      ansible.builtin.assert:
        that:
          - item in ansible_facts.packages
        fail_msg: "Gnome package {{ item }} is missing"
        quiet: true
      loop: "{{ gnome_packages[ansible_distribution] }}"

    # check removed packages
    - name: Test removed gnome packages
      ansible.builtin.assert:
        that:
          - item not in ansible_facts.packages
        fail_msg: "Obsolete Gnome package {{ item }} is still rpesent"
        quiet: true
      loop: "{{ obsolete_packages[ansible_os_family] }}"

    # assert graphical target
    - name: Get current target
      ansible.builtin.stat:
        path: /etc/systemd/system/default.target
      register: default_target

    - name: Test graphical target
      ansible.builtin.assert:
        that:
          - default_target.stat.islnk == true
          - default_target.stat.lnk_target == "/usr/lib/systemd/system/graphical.target"
        fail_msg: "Graphical target not set as default"
        quiet: true

    # assert X11
    - name: "Get gdm config"
      ansible.builtin.command:
        cmd: "cat {{ gdm_config_file[ansible_distribution] }}"
      register: gdm_config
      changed_when: false

    - name: Assert X11 is set
      ansible.builtin.assert:
        that:
          - "'WaylandEnable=false' in gdm_config.stdout_lines"
          - "'DefaultSession=gnome-xorg.desktop' in gdm_config.stdout_lines"
        fail_msg: "One or both of the expected lines are not present in {{ gdm_config_file[ansible_distribution] }}"
        success_msg: "Both expected lines are present in {{ gdm_config_file[ansible_distribution] }}"
        quiet: true

    # asser gnome base settings
    # assert installed extensions´
    # assert enabled extensions
    # assert disabled extensions
    # assert gnome themes
    # assert configured profile picture
    # TODO implement absent version of this role
