---

# tasks file for gnome_themes

- name: Get local users home dir
  ansible.builtin.user:
    name: "{{ local_user }}"
    state: present
  register: gnome_user

- name: Import gnome themes requirements
  ansible.builtin.import_tasks: gnome_themes_requirements.yaml

# diskspace error while cloning
- name: Clone repos from github
  ansible.builtin.git:
    repo: "{{ item.repo_url }}"
    dest: "{{ user_env_variables.USER_TMP_DIR }}{{ item.download_dir }}"
    single_branch: true
    version: "{{ item.branch }}"
    depth: 1
  loop: "{{ github_repo_themes }}"
  become: true
  become_user: "{{ gnome_user.name }}"

- name: "Install {{ item.name }}"
  ansible.builtin.command: "{{ item.install_cmd }}"
  args:
    chdir: "{{ user_env_variables.USER_TMP_DIR }}{{ item.install_dir }}"
  register: install_result
  changed_when: install_result.rc == 0
  loop: "{{ github_repo_themes }}"
  become: true
  become_user: "{{ gnome_user.name }}"

- name: Configure gnome themes
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ gnome_theme_settings }}"
  become: true
  become_user: "{{ gnome_user.name }}"

- name: Configure Wallpaper
  community.general.dconf:
    key: "{{ gnome_background_path }}{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ gnome_background_settings }}"
  become: true
  become_user: "{{ gnome_user.name }}"

...
