---

- name: Remove INI-formatted mount file
  become: true
  loop: "{{ mount_targets }}"
  ansible.builtin.file:
    path: "{{ smb_mount_file_path }}/{{ smb_mnt_point }}-{{ item.mount }}.mount"
    state: "absent"

- name: Remove INI-formatted automount file
  become: true
  loop: "{{ mount_targets }}"
  ansible.builtin.file:
    path: "{{ smb_mount_file_path }}/{{ smb_mnt_point }}-{{ item.mount }}.automount"
    state: "absent"

- name: Reload systemd service
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Remove mount targets
  become: true
  loop: "{{ mount_targets }}"
  ansible.builtin.file:
    path: "/{{ (smb_mnt_point, item.mount) | ansible.builtin.path_join }}"
    state: "absent"

- name: Remove credentials file
  become: true
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ smb_credentials_file }}"
    state: "absent"

- name: Remove required packages on debian based distros
  when: ansible_distribution in debian_based_distros
  become: true
  ansible.builtin.apt:
    name: "{{ smb_install_apt_packages }}"
    state: absent
  notify: Reboot Host

- name: Remove required packages on redhat based distros
  when: ansible_distribution in rhel_based_distros
  become: true
  ansible.builtin.dnf:
    name: "{{ smb_install_dnf_packages }}"
    state: absent

...
