---

# tasks file for smb

- name: Run smb mount setup
  when: state == "present"
  ansible.builtin.import_tasks:
    file: smb_present.yml

- name: Remove smb mount setup
  when: state == "absent"
  ansible.builtin.import_tasks:
    file: smb_absent.yml

...
