---

# tasks file for smb
- name: Install required packages
  ansible.builtin.package:
    name: "{{ install_packages }}"
    state: present
  become: true

- name: Add fileserver to hosts
  ansible.builtin.lineinfile:
    path: "{{ hosts_file_path }}"
    line: "{{ hosts_entry }}"
    create: true
    mode: "0644"
  become: true

- name: Write credentials
  ansible.builtin.copy:
    content: |
      username={{ smb_login }}
      password={{ smb_password }}
    dest: "{{ (user_home_path, smb_credentials_file) | ansible.builtin.path_join }}"
    owner: root
    group: root
    mode: "0600"
  become: true

- name: Create mount target
  ansible.builtin.file:
    path: "{{ (mnt_point, item.mount) | ansible.builtin.path_join }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop: "{{ target }}"
  become: true

- name: Copy mount template to remote host
  ansible.builtin.template:
    src: mountfile.mount.j2
    dest: "{{ (systemd_mount_file_path, mnt_point + '-' + item.mount + mount_file_ext) | ansible.builtin.path_join }}"
    mode: preserve
  loop: "{{ target }}"
  become: true

- name: Copy automount template to remote host
  ansible.builtin.template:
    src: mountfile.automount.j2
    dest: "{{ (systemd_mount_file_path, mnt_point + '-' + item.mount + auto_mount_file_ext) | ansible.builtin.path_join }}"
    mode: preserve
  loop: "{{ target }}"
  become: true

- name: Enable auto-mount file
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ mnt_point }}-{{ item.mount }}.automount"
    state: started
    enabled: true
  loop: "{{ target }}"
  become: true

- name: Reboot the host and continue playbook
  ansible.builtin.reboot:
    msg: Reboot initiated by Ansible
    pre_reboot_delay: 5
    reboot_timeout: 300
  become: true

- name: Wait for the host to come back online
  ansible.builtin.wait_for_connection:
    timeout: 300

- name: Copy file using smb shares
  ansible.builtin.command: cp /{{ (mnt_point, dummy_path, dummy_file) | ansible.builtin.path_join }} {{ (ansible_env.HOME, dummy_target) | ansible.builtin.path_join }}
  register: copy_result
  changed_when: copy_result.rc == 0
  notify: Clean up after test

...
