---

# tasks file for smb
- name: Import SMB requirements
  ansible.builtin.import_tasks: smb_requirements.yaml

- name: Copy mount template to remote host
  ansible.builtin.template:
    src: mountfile.mount.j2
    dest: /etc/systemd/system/{{ mnt_point }}-{{ item.mount }}.mount
    mode: preserve
  loop: "{{ target }}"
  become: true

- name: Copy automount template to remote host
  ansible.builtin.template:
    src: mountfile.automount.j2
    dest: /etc/systemd/system/{{ mnt_point }}-{{ item.mount }}.automount
    mode: preserve
  loop: "{{ target }}"
  become: true

- name: Enable auto-mount file
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ mnt_point }}-{{ item.mount }}.automount"
    state: started
    enabled: true
  loop: "{{ target }}"
  become: true

- name: Reboot the host and continue playbook
  ansible.builtin.reboot:
    msg: Reboot initiated by Ansible
    pre_reboot_delay: 5
    reboot_timeout: 300
  become: true

- name: Wait for the host to come back online
  ansible.builtin.wait_for_connection:
    timeout: 300
  become_user: "{{ local_user }}"

- name: Check home dir for "{{ local_user }}"
  ansible.builtin.debug:
    msg: "This is {{ ansible_env.USER }} currrent home dir: {{ ansible_env.HOME }}"
  become_user: "{{ local_user }}"

- name: Copy file using smb shares
  ansible.builtin.command: cp /{{ mnt_point }}/library/dummy_data/setup_check.txt "{{ ansible_env.HOME }}/Documents/"
  register: copy_result
  changed_when: copy_result.rc == 0
  notify: Clean up after test
  become_user: "{{ local_user }}"

...