---

# tasks file for smb

- name: Install required packages on redhat based distros
  when: "ansible_distribution in ['RedHat', 'CentOS', 'AlmaLinux']"
  become: true
  ansible.builtin.dnf:
    name: "{{ install_packages }}"
    state: present
    update_cache: true

- name: Install required packages on debian based distros
  when: "ansible_distribution in ['Ubuntu', 'Debian']"
  become: true
  ansible.builtin.apt:
    name: "{{ install_packages }}"
    state: present
    update_cache: true

- name: Add fileserver host to system/vm host
  ansible.builtin.lineinfile:
    path: "{{ hosts_file_path }}"
    line: "{{ hosts_entry }}"
    state: present
    mode: "0644"
  become: true

- name: Write credentials
  ansible.builtin.copy:
    content: |
      username={{ smb_login }}
      password={{ smb_password }}
    dest: "{{ (user_home_path, smb_credentials_file) | ansible.builtin.path_join }}"
    owner: root
    group: root
    mode: "0600"
  become: true

- name: Create mount target
  ansible.builtin.file:
    path: "{{ (mnt_point, item.mount) | ansible.builtin.path_join }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop: "{{ target }}"
  become: true

- name: Copy mount template to remote host
  ansible.builtin.template:
    src: mountfile.mount.j2
    dest: "{{ (systemd_mount_file_path, mnt_point + '-' + item.mount + mount_file_ext) | ansible.builtin.path_join }}"
    mode: preserve
  loop: "{{ target }}"
  become: true

- name: Copy automount template to remote host
  ansible.builtin.template:
    src: mountfile.automount.j2
    dest: "{{ (systemd_mount_file_path, mnt_point + '-' + item.mount + auto_mount_file_ext) | ansible.builtin.path_join }}"
    mode: preserve
  loop: "{{ target }}"
  become: true

- name: Enable auto-mount file
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: "{{ mnt_point }}-{{ item.mount }}.automount"
    state: started
    enabled: true
  loop: "{{ target }}"
  become: true

...
