---

# tasks file for smb

- name: Install required packages on redhat based distros
  when: ansible_distribution in rhel_based_distros
  become: true
  ansible.builtin.dnf:
    name: "{{ smb_install_dnf_packages }}"
    state: present
    update_cache: true

- name: Install required packages on debian based distros
  when: ansible_distribution in debian_based_distros
  become: true
  ansible.builtin.apt:
    name: "{{ smb_install_deb_packages }}"
    state: present
    update_cache: true
  notify: Reboot Host

- name: Add fileserver host to system/vm host
  become: true
  ansible.builtin.lineinfile:
    path: "{{ smb_hosts_file_path }}"
    line: "{{ smb_hosts_entry }}"
    state: present
    mode: "0644"

# TODO handle credential files in more safe way
- name: Write credentials
  become: true
  ansible.builtin.copy:
    content: |
      username={{ smb_login }}
      password={{ smb_password }}
    dest: "{{ (ansible_env.HOME, smb_credentials_file) | ansible.builtin.path_join }}"
    owner: root
    group: root
    mode: "0600"

- name: create mount file operations
  ansible.builtin.include_tasks: mount_files.yml
  loop: "{{ mount_targets }}"

...
