---
- name: Get file stats
  ansible.builtin.stat:
    path: "/{{ (smb_mnt_point, item.mount) | ansible.builtin.path_join }}"
  register: mount_stat

- name: Show data
  ansible.builtin.debug:
    var: mount_stat

- name: Show ansible_user
  ansible.builtin.debug:
    var: "{{ ansible_user }}"

- name: Create mount targets
  become: true
  ansible.builtin.file:
    path: "/{{ (smb_mnt_point, item.mount) | ansible.builtin.path_join }}"
    state: directory
    owner: "root"  # "{{ ansible_user }}"
    group: "root"  # "{{ ansible_user }}"
    mode: "0755"

- name: Generate INI-formatted mount file
  become: true
  ansible.builtin.blockinfile:
  # TODO move combined paths to defaults.yml
    path: "{{ (smb_systemd_mount_file_path, smb_mnt_point + '-' + item.mount + smb_mount_file_ext) | ansible.builtin.path_join }}"
    block: |
      # TODO research parser from yaml to ini
      {% for section, options in mount_file.items() %}
      [{{ section }}]
      {% for key, value in options.items() %}
      {{ key }}={{ value }}
      {% endfor %}

      {% endfor %}
    mode: "0644"
    create: true

- name: Generate INI-formatted automount file
  become: true
  ansible.builtin.blockinfile:
  # TODO move combined paths to defaults.yml
    path: "{{ (smb_systemd_mount_file_path, smb_mnt_point + '-' + item.mount + smb_automount_file_ext) | ansible.builtin.path_join }}"
    block: |
      # TODO research parser from yaml to ini
      {% for section, options in smb_automount_file.items() %}
      [{{ section }}]
      {% for key, value in options.items() %}
      {{ key }}={{ value }}
      {% endfor %}

      {% endfor %}
    mode: "0644"
    create: true

- name: Enable auto-mount file
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: "{{ smb_mnt_point }}-{{ item.mount }}.automount"
    state: started
    enabled: true
