---

# tasks file for smb_server

- name: Create virtual environment
  ansible.builtin.command:
    cmd: "python3 -m virtualenv ~/.venvs/smb"
    creates: "~/.venvs/smb"

- name: Install required pip packages
  ansible.builtin.pip:
    name: "{{ item }}"
    virtualenv: "~/.venvs/smb"
  loop: "{{ smb_server_install_pip_packages }}"

- name: Create user Account
  ansible.builtin.user:
    name: "{{ smb_login }}"
    password: "{{ smb_password | password_hash('sha512') }}"
    create_home: true
    update_password: on_create
    state: present

- name: Create samba users
  become: true
  ansible.builtin.shell: >
    set -e -o pipefail
    && (pdbedit --user={{ smb_login }} 2>&1 > /dev/null)
    || (echo '{{ smb_password }}'; echo '{{ smb_password }}')
    | smbpasswd -s -a {{ smb_login }}
  args:
    executable: /bin/bash
  register: samba_create_users
  changed_when: "'Added user' in samba_create_users.stdout"

- name: Create shares
  ansible.builtin.file:
    path: "/home/{{ smb_login }}/sambashares/{{ item.share }}"
    state: directory
    owner: "{{ smb_login }}"
    group: "{{ smb_login }}"
    mode: "0744"  # TODO research why 0644 doesn't work here
  loop: "{{ mount_targets }}"

- name: Configure smb.conf
  ansible.builtin.template:
    src: smb.conf.j2
    dest: "{{ smb_server_config_path }}"
    mode: "0644"
  notify: Restart SMB

...
