---

- name: "Clone extensions from github"
  ansible.builtin.git:
    repo: "{{ item.repo_url }}"
    dest: "{{ (user_install_dir, item.download_dir) | ansible.builtin.path_join }}"
    single_branch: true
    version: "{{ item.branch }}"
    depth: 1
  register: git_result

- name: Update installer permissions
  ansible.builtin.file:
    path: "{{ (user_install_dir, item.install_dir, item.installer) | ansible.builtin.path_join }}"
    mode: "0755"
  when: git_result.changed

- name: "Install extensions from github"
  ansible.builtin.command: "{{ item.install_cmd }}"
  args:
    chdir: "{{ (user_install_dir, item.install_dir) | ansible.builtin.path_join }}"
  register: install_result
  changed_when: install_result.rc == 0
  when: git_result.changed

...
