---
# tasks file for gnome_config
# TODO check first if gnome is installed -> install if not
# TODO gnome default install highly distro dependent
# evry distro needs their specific install method for gnome and GUI ingeneral
# TODO decide: one role per gnome app or one role for all gnome-apps
# gnome apps: gnome shell, gnome terminal, gedit, nautilus, system-monitor, disk-usage-analyzer, disks, gnome-calendar
# additional apps without own config: gnome-tweaks, gnome-extensions, dconf-editor
# check values using dconf module

- name: Update repos on debian based distros
  when: ansible_distribution in debian_based_distros
  become: true
  ansible.builtin.command:
    cmd: "apt update --fix-missing"
  register: result
  changed_when: "'Fix not found' not in result.stdout"

- name: Install Gnome desktop
  become: true
  ansible.builtin.package:
    name: "{{ gnome_package[ansible_distribution] }}"
    state: present

- name: Remove obsolete Gnome packages
  become: true
  loop: "{{ obsolete_packages }}"
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent

- name: Install additional Gnome packages
  loop: "{{ additional_packages[ansible_distribution] }}"
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present

- name: Install Gnome extensions
  loop: "{{ gnome_extensions[ansible_distribution] }}"
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
 
- name: Get Gnome version
  ansible.builtin.shell:
    cmd: "gnome-shell --version | awk '{print $3}' | cut -d'.' -f1"
  register: gnome_major_version

- name: Ensure default target is graphical
  become: true
  ansible.builtin.command:
    cmd: systemctl set-default graphical.target
  register: result
  changed_when: result.rc == 0
  notify: Reboot Host

- name: Install required packages for dconf module
  ansible.builtin.package:
    name: "{{ prerequired_packages }}"
    state: present
  become: true
 
# - name: Ignore PEP 668
#   when: ansible_distribution == "Debian"
#   become: true
#   ansible.builtin.file:
#     path: /usr/lib/python3.11/EXTERNALLY-MANAGED
#     state: absent

# - name: Install pip packages
#   ansible.builtin.pip:
#     name: "{{ pip_packages }}"
#     state: present

- name: Configure gnome-settings
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ gnome_initial_settings[gnome_major_version.stdout] }}"

# INFO partly broken visible columns show no effect
# - name: Configure nautilus
#   community.general.dconf:
#     key: "{{ item.key }}"
#     value: "{{ item.value }}"
#   with_dict: "{{ nautilus_settings }}"

# - name: Configure text editor
#   community.general.dconf:
#     key: "{{ item.key }}"
#     value: "{{ item.value }}"
#   with_dict: "{{ text_editor_settings }}"

# - name: Add terminal profile
#   community.general.dconf:
#     key: "{{ terminal_profile_list }}"
#     value: "['{{ terminal_profile_uuid }}']"

# - name: Configure terminal profile
#   community.general.dconf:
#     key: "{{ terminal_profile_path }}{{ item.key }}"
#     value: "{{ item.value }}"
#   with_dict: "{{ terminal_profile_settings }}"

# - name: Configure terminal legacy settings
#   community.general.dconf:
#     key: "{{ item.key }}"
#     value: "{{ item.value }}"
#   with_dict: "{{ terminal_legacy_settings }}"
