---
# tasks file for gnome_config
# TODO gnome default install highly distro dependent
# evry distro needs their specific install method for gnome and GUI ingeneral
# TODO decide: one role per gnome app or one role for all gnome-apps
# gnome apps: gnome shell, gnome terminal, gedit, nautilus, system-monitor, disk-usage-analyzer, disks, gnome-calendar
# check values using dconf module

# TODO check potential speed improvement
- name: Gather package facts
  ansible.builtin.package_facts:

- name: Install additional repos
  loop: "{{ additional_repos[ansible_distribution] }}"
  when: ansible_os_family == "RedHat" and item not in ansible_facts.packages
  become: true
  ansible.builtin.dnf:
    name: "{{ item }}"
    disable_gpg_check: true
    update_cache: true

- name: Install dependencies 
  loop: "{{ dependencies }}"
  when: item not in ansible_facts.packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  become: true

- name: Install Gnome desktop
  when: gnome_package[ansible_distribution] not in ansible_facts.packages
  become: true
  ansible.builtin.package:
    name: "{{ gnome_package[ansible_distribution] }}"
    state: present
    update_cache: true

- name: Remove obsolete Gnome packages
  become: true
  loop: "{{ obsolete_packages[ansible_os_family] }}"
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent

- name: Set default target to graphical
  become: true
  ansible.builtin.file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link
  notify: Reboot Host

- name: Get Gnome version
  ansible.builtin.shell:
    cmd: "gnome-shell --version | awk '{print $3}' | cut -d'.' -f1"
  register: gnome_major_version
  changed_when: false

- name: Install additional Gnome packages for rhel based distros
  when: ansible_os_family == "RedHat" and item not in ansible_facts.packages
  loop: "{{ additional_packages[ansible_distribution] }}"
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present

- name: Install additional Gnome packages for Debian based distros
  when: ansible_os_family == "Debian" and item not in ansible_facts.packages
  loop: "{{ additional_packages[ansible_distribution] }}"
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present

- name: Configure gnome-settings
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_dict: "{{ gnome_initial_settings[gnome_major_version.stdout] }}"

# TODO move to dictionary and figure how how to make it work with the other values in on task
- name: Set keyboard layouts
  ansible.builtin.dconf:
    key: "/org/gnome/desktop/input-sources/sources"
    value: "[('xkb', 'de'), ('xkb', 'us')]"

- name: Install Gnome extensions
  loop: "{{ gnome_extensions[ansible_distribution] }}"
  when: item not in ansible_facts.packages
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present

- name: Find user installed GNOME extensions
  ansible.builtin.shell:
    cmd: "ls ~/.local/share/gnome-shell/extensions/"
  register: user_gnome_extensions_list
  changed_when: false
  failed_when: user_gnome_extensions_list.rc not in [0, 2]

- name: Install extensions from github
  loop: "{{ github_repo_extensions }}"
  when: item.name not in user_gnome_extensions_list.stdout_lines and ansible_distribution not in item.exclude_distro
  ansible.builtin.include_tasks:
    file: extensions_github.yml
  loop_control:
    label: "{{ item.name }}" 

- name: Find installed GNOME extensions
  ansible.builtin.shell:
    cmd: "ls ~/.local/share/gnome-shell/extensions/ && ls /usr/share/gnome-shell/extensions"
  register: gnome_extensions_list
  changed_when: false

- name: Enable installed extensions
  ansible.builtin.dconf:
    key: "/org/gnome/shell/enabled-extensions"
    value: "{{ gnome_extensions_list.stdout_lines | to_json }}"

# INFO partly broken visible columns show no effect
# - name: Configure nautilus
#   community.general.dconf:
#     key: "{{ item.key }}"
#     value: "{{ item.value }}"
#   with_dict: "{{ nautilus_settings }}"

# - name: Configure text editor
#   community.general.dconf:
#     key: "{{ item.key }}"
#     value: "{{ item.value }}"
#   with_dict: "{{ text_editor_settings }}"

# - name: Add terminal profile
#   community.general.dconf:
#     key: "{{ terminal_profile_list }}"
#     value: "['{{ terminal_profile_uuid }}']"

# - name: Configure terminal profile
#   community.general.dconf:
#     key: "{{ terminal_profile_path }}{{ item.key }}"
#     value: "{{ item.value }}"
#   with_dict: "{{ terminal_profile_settings }}"

# - name: Configure terminal legacy settings
#   community.general.dconf:
#     key: "{{ item.key }}"
#     value: "{{ item.value }}"
#   with_dict: "{{ terminal_legacy_settings }}"
