---

# Assing profile picture

- name: Get users list
  ansible.builtin.getent:
    database: passwd

# INFO get user names enabled for login
- name: Extract usernames with valid shell
  loop: "{{ getent_passwd | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  when: item.value[5] in valid_shells
  ansible.builtin.set_fact:
    shell_users: "{{ shell_users | default([]) + [item.key] }}"

- name: Copy profile pictures
  when: shell_user in profile_picture.keys()
  become: true
  loop: "{{ shell_users }}"
  loop_control:
    loop_var: shell_user
  ansible.builtin.copy:
    src: "{{ profile_picture[shell_user] }}"
    dest: "{{ picture_dest_path }}/{{ shell_user }}"
    owner: root
    group: root
    mode: '0344'

- name: Create the shell_user configuration file
  when: shell_user in profile_picture.keys()
  become: true
  loop: "{{ shell_users }}"
  loop_control:
    loop_var: shell_user
  ansible.builtin.template:
    src: gnome_profile.j2
    dest: "{{ profile_config_path }}/{{ shell_user }}"
    owner: root
    group: root
    mode: "0600"  # 0600 by default and changes to 0644 after first login

...
