---

# task file for profile pictures

- name: Copy profile pictures
  become: true
  ansible.builtin.copy:
    src: "{{ (picture_src_path, shell_user) | ansible.builtin.path_join }}"
    dest: "{{ (picture_dest_path, shell_user) | ansible.builtin.path_join }}"
    owner: root
    group: root
    mode: '0344'

- name: get profile file stats
  become: true
  ansible.builtin.stat:
    path: /var/lib/AccountsService/users/{{ shell_user }}
  register: file_stats
  failed_when: false

- name: Show stats
  ansible.builtin.debug:
    var: file_stats
  failed_when: false

# TODO fix Idempotency check
- name: Create the shell_user configuration file
  become: true
  ansible.builtin.copy:
    content: |
      [User]
      Session=
      Icon={{ (picture_dest_path, shell_user) | ansible.builtin.path_join }}
      SystemAccount=false
    dest: /var/lib/AccountsService/users/{{ shell_user }}
    owner: root
    group: root
    mode: 0600

...
