---

# task file for profile pictures

- name: Copy profile pictures
  become: true
  ansible.builtin.copy:
    src: "{{ (picture_src_path, shell_user) | ansible.builtin.path_join }}"
    dest: "{{ (picture_dest_path, shell_user) | ansible.builtin.path_join }}"
    owner: root
    group: root
    mode: '0344'

- name: Create the shell_user configuration file
  become: true
  ansible.builtin.copy:
    content: |
      [User]
      Session=
      Icon={{ (picture_dest_path, shell_user) | ansible.builtin.path_join }}
      SystemAccount=false
    dest: /var/lib/AccountsService/users/{{ shell_user }}
    owner: root
    group: root
    mode: 0644

...
