---

# pre-requirements file

- name: Enable CRB (CentOS Extras) repository
  when: ansible_os_family == redhat
  become: true
  community.general.dnf_config_manager:
    name: crb
    state: enabled

- name: Install additional repos
  loop: "{{ additional_rhel_repos }}"
  loop_control:
    loop_var: repo
  when: ansible_os_family == redhat and repo not in ansible_facts.packages
  become: true
  ansible.builtin.dnf:
    name: "{{ repo }}"
    disable_gpg_check: true
    update_cache: true

- name: Install global dependencies 
  loop: "{{ dependencies[ansible_os_family] }}"
  when: item not in ansible_facts.packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  become: true

- name: Get current system locale
  ansible.builtin.shell:
    cmd: "localectl status | awk '/LANG/{print $3}' | cut -d'=' -f2"
  register: current_locale
  changed_when: false
  check_mode: no

# alma9 box missing default locals -> extension system-monitor fails to activate if locals are missing
- name: "Set system locale to {{ system_local_lang }}"
  when: ansible_distribution == "AlmaLinux" and current_locale.stdout != system_local_lang
  become: true
  ansible.builtin.command:
    cmd: "localectl set-locale {{ system_local_lang }}"
  register: set_locale_result
  changed_when: set_locale_result.rc == 0
