---

- name: Converge
  hosts: all

  vars:
    dummy_file_path_server: "/mnt/library/dummy_data/setup_check.txt"
    dummy_file_path_local: "/tmp/setup_check.txt"

  tasks:
    - name: Reboot the host and continue playbook
      ansible.builtin.reboot:
        msg: Reboot initiated by Ansible
        pre_reboot_delay: 5
        reboot_timeout: 300
      become: true

    - name: Wait for the host to come back online
      ansible.builtin.wait_for_connection:
        timeout: 300

    - name: Copy test file to host
      ansible.builtin.copy:
        src: "{{ dummy_file_path_server }}"
        dest: "{{ dummy_file_path_local }}"
        mode: "0600"

    - name: Remove test file
      ansible.builtin.file:
        path: "{{ dummy_file_path_local }}"
        state: absent
