---

- name: Clean Up
  hosts: client

  pre_tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:

  tasks:
    - name: Roll back changes
      ansible.builtin.include_role:
        name: gnome_setup
        tasks_from: main.yml
      vars:
        gnome_setup_state: absent

...
