---

- name: Create and configure gnome desktop
  hosts: client
  vars:
    system_local_lang: "en_US.UTF-8"

  debugger: on_failed

  pre_tasks:
    - name: Include dependencies
      ansible.builtin.include_role:
        name: gnome_setup
        tasks_from: dependencies.yml

  tasks:
    - name: Include gnome role present
      ansible.builtin.include_role:
        name: gnome_setup
      vars:
        gnome_setup_state: present

...
