---

# tasks file for gnome_extensions requirements

- name: Install lm_sensors for freon
  ansible.builtin.package:
    name: lm_sensors
    state: present
  become: true

- name: Install gettext for Tiling-Assistant
  ansible.builtin.package:
    name: gettext
    state: present
  become: true

...
