# INFO add additional repos
- name: Enable RPM Fusion Free repository
  ansible.builtin.yum_repository:
    name: rpmfusion-free
    description: RPM Fusion Free for Fedora $releasever
    metalink: https://mirrors.rpmfusion.org/metalink?repo=free-fedora-$releasever&arch=$basearch
    enabled: true
    metadata_expire: 14
    gpgcheck: true
    repo_gpgcheck: false
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever
    state: present
  become: true

- name: Enable RPM Fusion Non-Free repository
  ansible.builtin.yum_repository:
    name: rpmfusion-nonfree
    description: RPM Fusion Non-Free for Fedora $releasever
    metalink: https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-$releasever&arch=$basearch
    enabled: true
    metadata_expire: 14
    gpgcheck: true
    repo_gpgcheck: false
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever
    state: present
  become: true

- name: Install Flatpak
  ansible.builtin.dnf:
    name: flatpak
    state: present
  become: true

- name: Add Flathub remote
  ansible.builtin.command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  register: command_result
  changed_when: command_result.rc == 0
  become: true