- name: Set system-wide environment variable
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: "{{ item.key }}={{ item.value }}"
    create: true
    state: present
    mode: "0644"
  with_dict: "{{ global_env_variables }}"
  become: true

# TODO save user home dir in a general available way
- name: Get local users home dir
  ansible.builtin.user:
    name: "{{ local_user }}"
    state: present
  register: this_user

- name: Set user environment variable
  ansible.builtin.lineinfile:
    path: "{{ this_user.home }}/.bashrc"
    line: "{{ item.key }}={{ item.value }}"
    create: true
    state: present
    mode: "0644"
  with_dict: "{{ user_env_variables }}"
  become: true
  become_user: "{{ local_user }}"
