# INFO set dnf options
- name: Set max_parallel_downloads for dnf
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: '^max_parallel_downloads='
    line: 'max_parallel_downloads=10'
    state: present
  become: true

- name: Set fastestmirror=true in dnf.conf
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: '^fastestmirror='
    line: 'fastestmirror=true'
    state: present
  become: true

- name: Set deltarpm=true in dnf.conf
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: '^deltarpm='
    line: 'deltarpm=true'
    state: present
  become: true

- name: Set host name "{{ host_name }}"
  ansible.builtin.hostname:
    name: "{{ host_name }}"
  become: true
