---
# tasks file for initial_setup_fedora
- name: Import inital_options
  ansible.builtin.import_tasks: inital_options.yaml

- name: Import inital_updates
  ansible.builtin.import_tasks: initial_updates.yaml

- name: Import additional_repos
  ansible.builtin.import_tasks: additional_repos.yaml

- name: Reboot the host and continue playbook
  ansible.builtin.reboot:
    msg: Reboot initiated by Ansible
    pre_reboot_delay: 5
    reboot_timeout: 300
  become: true

- name: Wait for the host to come back online
  ansible.builtin.wait_for_connection:
    timeout: 300
  become_user: "{{ ansible_user_id }}"

- name: Additional repos
  ansible.builtin.import_tasks: additional_repos.yaml

...
