---

# tasks file for smb_server
# TODO streamline paths
# TODO streamline distro checks

- name: Install required packages on redhat based distros
  when: "ansible_distribution in ['RedHat', 'CentOS', 'AlmaLinux']"
  become: true
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ install_packages }}"

- name: Install required packages on debian based distros
  when: "ansible_distribution in ['Ubuntu', 'Debian']"
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ install_packages }}"

- name: Install required pip packages
  ansible.builtin.pip:
    name: passlib

- name: Create user Account
  ansible.builtin.user:
    name: "{{ smb_login }}"
    password: "{{ smb_password | password_hash('sha512') }}"
    create_home: true
    update_password: on_create
    state: present

- name: shell - create samba users
  ansible.builtin.shell: >
    set -e -o pipefail
    && (pdbedit --user={{ smb_login }} 2>&1 > /dev/null)
    || (echo '{{ smb_password }}'; echo '{{ smb_password }}')
    | smbpasswd -s -a {{ smb_login }}
  args:
    executable: /bin/bash
  register: samba_create_users
  changed_when: "'Added user' in samba_create_users.stdout"

- name: create shares
  ansible.builtin.file:
    path: "/home/{{ smb_login }}/sambashares/{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - usb_backup
    - documents
    - learning
    - library
    - ressources

- name: Get information about the file
  ansible.builtin.stat:
    path: "/home/{{ smb_login }}/sambashares/documents/test.txt"
  register: file_info

- name: Create test file
  when: not file_info.stat.exists
  ansible.builtin.file:
    path: "/home/{{ smb_login }}/sambashares/documents/test.txt"
    state: touch
    mode: "0755"

- name: Configure smb.conf
  ansible.builtin.template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    mode: "0644"
  notify: Restart SMB

...
