---
dependency:
  name: galaxy    
driver:
  name: vagrant
  provider:
    name: virtualbox
    type: virtualbox
lint: |
  set -e
  yamllint
  ansible-lint
platforms:
  - name: Rocky9
    box: rockylinux/9
    memory: 2048
    cpus: 2
    interfaces:
      - auto_config: true
        network_name: private_network
        type: "static"
        ip: "192.168.56.30"
    provider_raw_config_args:
      - "customize ['modifyvm', :id, '--uartmode1', 'disconnected']"
    groups:
      - client
  - name: smbserver
    box: ubuntu/jammy64
    memory: 1024
    cpus: 1
    interfaces:
      - auto_config: true
        network_name: private_network
        type: "static"
        ip: "192.168.56.200"
    provider_raw_config_args:
      - "customize [ 'modifyvm', :id, '--uartmode1', 'disconnected']"
    groups:
      - server
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        debian_based_distros: ["Debian", "Ubuntu"]
        rhel_based_distros: ["RedHat", "CentOS", "AlmaLinux"]
  config_options:
    defaults:
      gathering: smart
      fact_caching_timeout: 3600
      fact_caching: jsonfile
      fact_caching_connection: /tmp/ansible_fact_cache
      stdout_callback: ansible.posix.debug
      callbacks_enabled: ansible.posix.profile_tasks
    connection:
      # WARNING disable "requiretty" in hosts sudoers file in case of errors 
      pipelining: true
    env:
      PY_COLORS: "1"
      ANSIBLE_FORCE:COLOR: "1"
verifier:
  name: ansible
scenario:
  test_sequence:
      - dependency
      - syntax
      - create
      - prepare
      - converge
      - idempotence
      - side_effect
      - verify
      - cleanup
      - destroy
