# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Gnome test

on:
  push:
    branches: [ "gnome-role-tdd" ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ "gnome-role-tdd" ]
permissions:
  contents: read

jobs:
  gnome:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ["3.10"]
        molecule-scenario: ["test_centosstream9", "test_rocky9", "test_alma9", "test_ubuntu2204", "test_debian12"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install VirtualBox
      run: |
        wget -O- https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo gpg --dearmor --yes --output /usr/share/keyrings/oracle-virtualbox-2016.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] http://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list
        sudo apt-get update
        sudo apt-get install -y linux-headers-$(uname -r) dkms
        sudo apt-get install gcc-12 virtualbox-7.0 -y

    - name: Verify VirtualBox installation
      run: VBoxManage --version

    - name: install vagrant
      run: |
        VAGRANT_VERSION=$(curl -sL https://releases.hashicorp.com/vagrant/ | grep -oP 'vagrant/\K[\d.]+' | head -1)
        wget https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}_x86_64.deb
        sudo apt install ./vagrant_${VAGRANT_VERSION}_x86_64.deb
        
        # # Get vagrant gpg key
        # wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        # echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        # sudo apt-get update && sudo apt-get install vagrant -y

    - name: Verify Vagrant installation
      run: vagrant --version

    - name: Set Vagrant default provider to VirtualBox
      run: echo "VAGRANT_DEFAULT_PROVIDER=virtualbox" >> $GITHUB_ENV

    - name: Add VirtualBox and Vagrant to PATH
      run: |
        echo "/usr/local/bin" >> $GITHUB_PATH
        echo "/usr/bin" >> $GITHUB_PATH
        echo "/opt/vagrant/bin" >> $GITHUB_PATH

    - name: Check installed providers
      run: vagrant plugin list

    - name: Check VirtualBox status
      run: VBoxManage list runningvms

    - name: Run molecule test
      run: |
        cd gnome_setup
        molecule test -s ${{ matrix.molecule-scenario }}    
