# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: SMB mount test

on:
  push:
    branches: [ "smb-tdd" ]
  pull_request:
    branches: [ "smb-tdd" ]

permissions:
  contents: read

jobs:
  setup_smb_mounts:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]
        molecule-scenario: ["smb_mount_test_centosstream9", "smb_mount_test_rocky9", "smb_mount_test_alma9", "smb_mount_test_ubuntu2210", "smb_mount_test_debian12"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install VirtualBox
      run: |
        sudo apt-get install virtualbox

    - name: install vagrant
      run: |
        # Get vagrant gpg key
        wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt-get update && sudo apt-get install vagrant -y

    - name: Run molecule test
      run: |
        cd smb_mount
        molecule test -s ${{ matrix.molecule-scenario }}
