# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "smb-tdd" ]
  pull_request:
    branches: [ "smb-tdd" ]
  workflow_dispatch:
    branches: [ "smb-tdd" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: install vagrant
      run: |
        # Get vagrant gpg key
        wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt-get update && sudo apt-get install vagrant -y
    - name: Install ansible molecule
      run: |
        python -m pip install molecule ansible-core
        python -m pip install molecule ansible-lint
        python -m pip install "molecule-plugins[vagrant]"
        python -m pip install jmespath
    - name: Run molecule test
      run: |
        molecule test -s smb_mount_test
        