---

# variables for basic gnome config

# INFO some dictionary splits for each distro may seem redundant
# INFO this is intentional to enable deactivation on a per distro basis if neccessary to not break the whole testing setup

user_install_dir: "{{ (ansible_env.HOME, install_name) | ansible.builtin.path_join }}"

additional_rhel_repos:
  - name: rpmfusion-free
    gpg_key: "/usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-free-el-{{ ansible_distribution_major_version }}"
    src: "https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
  - name: rpmfusion-nonfree
    gpg_key: "/usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-nonfree-el-{{ ansible_distribution_major_version }}"
    src: "https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"

gnome_packages:
  "RedHat":
    - gnome-shell
    - gnome-themes-extra # includes Adwaita-dark
    - gnome-terminal
    - gnome-system-monitor
    - gnome-software
    - gnome-tweaks
    - gnome-user-docs
    - gnome-photos
    - gnome-font-viewer
    - gnome-extensions-app
    - gnome-control-center-filesystem
    - gnome-characters
    - gnome-devel-docs
    - gnome-disk-utility
    - baobab
  "Debian":
    - gnome-shell
    - gnome-themes-extra # includes Adwaita-dark
    - gnome-terminal
    - gnome-system-monitor
    - gnome-software
    - gnome-tweaks
    - gnome-user-docs
    - gnome-photos
    - gnome-font-viewer
    - gnome-shell-extension-prefs
    - gnome-control-center
    - gnome-characters
    - gnome-devel-docs
    - gnome-disk-utility
    - baobab

obsolete_packages:
  "RedHat":
    - gnome-tour
    - gnome-shell-extension-background-logo
    - gnome-remote-desktop
    - gnome-software-plugin-snap
    - gnome-startup-applications
  "Debian":
    - gnome-tour
    - gnome-shell-extension-background-logo
    # INFO gnome-remote-desktop is a part of gnome-control-center package
    - gnome-software-plugin-snap
    - gnome-startup-applications

gdm_config_file:
  "CentOS": "/etc/gdm/custom.conf"
  "AlmaLinux": "/etc/gdm/custom.conf"
  "Rocky": "/etc/gdm/custom.conf"
  "Ubuntu": "/etc/gdm3/custom.conf"
  "Debian": "/etc/gdm3/daemon.conf"

gnome_base_settings:
  "40":
    # update gnome formats to United Kingdom
    # obsolete if user theme gets added
    # "/org/gnome/desktop/interface/gtk-theme": "'Adwaita-dark'"
    # TODO test combining values like: << : *shape in combination with anchors
    "/system/locale/region": "'en_GB.UTF-8'"
    # TODO test if this works
    "/org/gnome/shell/extensions/dash-to-dock/disable-overview-on-startup": "true"
    "/org/gnome/desktop/interface/enable-hot-corners": "false"
    "/org/gnome/desktop/input-sources/sources": "[('xkb', 'de'), ('xkb', 'us')]"
    "/org/gnome/desktop/input-sources/sources/per-window": "false"
    "/org/gnome/desktop/input-sources/mru-sources": "[['xkb', 'de'], ['xkb', 'us']]"
    "/org/gnome/desktop/input-sources/xkb-options": "['caps:none']"
    "/org/gnome/desktop/wm/keybindings/activate-window-menu": "@as []"
    "/org/gnome/desktop/wm/preferences/action-middle-click-titlebar": "'minimize'"
    "/org/gnome/mutter/attach-modal-dialogs": "false"
    "/org/gnome/mutter/center-new-windows": "false"
    "/org/gnome/mutter/edge-tiling": "false"
    "/org/gnome/desktop/interface/clock-show-weekday": "true"
    "/org/gnome/desktop/interface/font-name": "'Cantarell Bold 11'"
    "/org/gnome/desktop/wm/preferences/titlebar-font": "'Carlito Bold Italic 11'"
    "/org/gnome/tweaks/show-extensions-notice": "false"
    "/org/gnome/desktop/wm/preferences/button-layout": "'close,maximize,minimize:appmenu'"
    "/org/gnome/software/download-updates": "false"
    "/org/gnome/software/first-run": "false"
  "42":
    # obsolete if user theme gets added
    # "/org/gnome/desktop/interface/gtk-theme": "'Adwaita-dark'"
    # "/org/gnome/shell/extensions/user-theme/name": "'Yaru-magenta-dark'"
    "/org/gnome/desktop/interface/color-scheme": "'prefer-dark'"
    "/org/gnome/desktop/interface/enable-hot-corners": "false"
    "/org/gnome/desktop/input-sources/sources": "[('xkb', 'de'), ('xkb', 'us')]"
    "/org/gnome/desktop/input-sources/sources/per-window": "false"
    "/org/gnome/desktop/input-sources/mru-sources": "[['xkb', 'de'], ['xkb', 'us']]"
    "/org/gnome/desktop/input-sources/xkb-options": "['caps:none']"
    "/org/gnome/desktop/wm/keybindings/activate-window-menu": "@as []"
    "/org/gnome/desktop/wm/preferences/action-middle-click-titlebar": "'minimize'"
    "/org/gnome/desktop/wm/preferences/titlebar-font": "'Carlito Bold Italic 11'"
    "/org/gnome/desktop/wm/preferences/button-layout": "'close,maximize,minimize:appmenu'"
    "/org/gnome/mutter/attach-modal-dialogs": "false"
    "/org/gnome/shell/overrides/attach-modal-dialogs": "false"
    "/org/gnome/mutter/center-new-windows": "false"
    "/org/gnome/desktop/interface/clock-show-weekday": "true"
    "/org/gnome/desktop/interface/font-name": "'Cantarell Bold 11'"
    "/org/gnome/tweaks/show-extensions-notice": "false"
    "/org/gnome/software/download-updates": "false"
    "/org/gnome/software/first-run": "false"
  "43":
    "/org/gnome/desktop/interface/color-scheme": "'prefer-dark'"
    # obsolete if user theme gets added
    # "/org/gnome/desktop/interface/gtk-theme": "'Adwaita-dark'"
    "/org/gnome/desktop/interface/enable-hot-corners": "false"
    "/org/gnome/desktop/input-sources/sources": "[('xkb', 'de'), ('xkb', 'us')]"
    "/org/gnome/desktop/input-sources/sources/per-window": "false"
    "/org/gnome/desktop/input-sources/mru-sources": "[['xkb', 'de'], ['xkb', 'us']]"
    "/org/gnome/desktop/input-sources/xkb-options": "['caps:none']"
    "/org/gnome/desktop/wm/keybindings/activate-window-menu": "@as []"
    "/org/gnome/desktop/wm/preferences/action-middle-click-titlebar": "'minimize'"
    "/org/gnome/desktop/wm/preferences/button-layout": "'close,maximize,minimize:appmenu'"
    "/org/gnome/desktop/wm/preferences/titlebar-font": "'Carlito Bold Italic 11'"
    "/org/gnome/mutter/attach-modal-dialogs": "false"
    "/org/gnome/shell/overrides/attach-modal-dialogs": "false"
    "/org/gnome/mutter/center-new-windows": "false"
    "/org/gnome/desktop/interface/clock-show-weekday": "true"
    "/org/gnome/desktop/interface/font-name": "'Cantarell Bold 11'"
    "/org/gnome/tweaks/show-extensions-notice": "false"
    "/org/gnome/software/download-updates": "false"
    "/org/gnome/software/first-run": "false"
    "/org/gnome/desktop/privacy/old-files-age": "30"
    "/org/gnome/desktop/privacy/recent-files-max-age": "30"
    "/org/gnome/desktop/privacy/remove-old-temp-files": "true"
    "/org/gnome/desktop/privacy/remove-old-trash-files": "true"

# TODO move to setup roles for specific app
text_editor_settings:
  "/org/gnome/TextEditor/highlight-current-line": "true"
  "/org/gnome/TextEditor/right-margin-position": "uint32 80"
  "/org/gnome/TextEditor/show-line-numbers": "true"
  "/org/gnome/TextEditor/show-map": "true"
  "/org/gnome/TextEditor/style-scheme": "'kate-dark'"
  "/org/gnome/TextEditor/style-variant": "'dark'"
  "/org/gnome/TextEditor/tab-width": "uint32 4"
  "/org/gnome/TextEditor/use-system-font": "true"

nautilus_settings:
  "/org/gnome/nautilus/icon-view/captions": "['detailed_type', 'size', 'date_modified_with_time']"
  "/org/gnome/nautilus/list-view/default-visible-columns": "['name', 'size', 'mime_type', 'date_modified']"
  "/org/gnome/nautilus/list-view/default-column-order": "['name', 'size', 'mime_type', 'date_modified_with_time', 'type', 'owner', 'group', 'permissions', 'where', 'date_modified', 'date_accessed', 'date_created', 'recency', 'starred']"
  "/org/gnome/nautilus/list-view/default-zoom-level": "'small'"
  "/org/gtk/gtk4/settings/file-chooser/sort-directories-first": "true"
  "/org/gtk/gtk4/settings/file-chooser/date-format": "'regular'"
  "/org/gtk/gtk4/settings/file-chooser/location-mode": "'path-bar'"
  "/org/gtk/gtk4/settings/file-chooser/show-hidden": "false"
  "/org/gtk/gtk4/settings/file-chooser/show-size-column": "true"
  "/org/gtk/gtk4/settings/file-chooser/show-type-column": "true"
  "/org/gtk/gtk4/settings/file-chooser/sort-column": "'name'"
  "/org/gtk/gtk4/settings/file-chooser/sort-order": "'ascending'"
  "/org/gtk/gtk4/settings/file-chooser/type-format": "'category'"
  "/org/gtk/gtk4/settings/file-chooser/view-type": "'list'"
  # INFO doesn't seem to work
  # "/org/gnome/nautilus/list-view/default-zoom-level/use-tree-view": "true"
  "/org/gnome/nautilus/preferences/default-folder-viewer": "'list-view'"
  "/org/gnome/nautilus/preferences/migrated-gtk-settings": "true"
  "/org/gnome/nautilus/preferences/search-filter-time-type": "'last_modified'"
  "/org/gnome/nautilus/preferences/show-create-link": "true"
  "/org/gnome/nautilus/preferences/show-delete-permanently": "true"
  "/org/gnome/nautilus/preferences/show-image-thumbnails": "'always'"
terminal_legacy_settings:
  "/org/gnome/terminal/legacy/new-terminal-mode": "'tab'"
terminal_profile_uuid: "5261d7f3-37ae-43cc-90e5-2139da18c41d"
terminal_profile_path: "/org/gnome/terminal/legacy/profiles:/:{{ terminal_profile_uuid }}/"
terminal_profile_list: "/org/gnome/terminal/legacy/profiles:/list"
terminal_profile_settings:
  "visible-name": "'default'"
  "background-color": "'rgb(28,28,28)'"
  "background-transparency-percent": "22"
  "bold-color": "'rgb(147,15,182)'"
  "bold-color-same-as-fg": "false"
  "bold-is-bright": "true"
  "cursor-background-color": "'rgb(84,85,139)'"
  "cursor-colors-set": "true"
  "cursor-foreground-color": "'rgb(163,101,181)'"
  "default-size-columns": "105"
  "default-size-rows": "32"
  "font": "'Liberation Mono 14'"
  "use-system-font": "false"
  "foreground-color": "'rgb(198,141,232)'"
  "highlight-background-color": "'rgb(128,105,128)'"
  "highlight-colors-set": "true"
  "highlight-foreground-color": "'rgb(214,90,232)'"
  "palette": "['rgb(23,20,33)', 'rgb(192,28,40)', 'rgb(38,162,105)', 'rgb(162,115,76)', 'rgb(18,72,139)', 'rgb(163,71,186)', 'rgb(42,161,179)', 'rgb(208,207,204)', 'rgb(94,92,100)', 'rgb(246,97,81)', 'rgb(51,209,122)', 'rgb(233,173,12)', 'rgb(42,123,222)', 'rgb(192,97,203)', 'rgb(51,199,222)', 'rgb(255,255,255)']"
  "scrollbar-policy": "'never'"
  "use-theme-colors": "false"
  "use-transparent-background": "true"
